### ISSUE TITLE
README should mention that invisible elements are ignored by default.

### ISSUE THREAD

**Issue by yjukaku** [jnicklas/capybara#1209]
This just bit me. Was wondering why some Capybara examples (like the README) have `find("#bla").visible?`  with an invisible element, but writing that caused an exception for me.

Also, maybe mention somewhere that you can pass in visible: false to a `find()` call.

**Comment by CamJN** [comment]
This hit me too today, I'd argue this should be in big bold letters throughout the documentation as it's completely counter-intuitive when you are using css (and possibly others, I'm not used to xpath) selectors for matching.
