### ISSUE TITLE
Contenteditable editing does not work within an iframe

### ISSUE THREAD

**Issue by rbu** [jnicklas/capybara#1259]
We upgraded to Capybara 2.2.1 to use the contenteditable feature to interact with [SCEditor](http://www.sceditor.com/), a JS rich text editor. It renders the editable body within an iframe.

Unfortunately, using node.set() does not work in a within_iframe block. We tried something along the lines of
```
  page.execute_script("$('iframe').attr('id', 'editor')")
  within_frame("editor") do
    node = find("p")
    node.set("fnord")
  end
```

It will defocus the currently selected element, but not change the focus inside the frame.

**Comment by twalpole** [comment]
Closing since this is an issue in selenium.  If it's ever fixed there it will start working in Capybara.
