### ISSUE TITLE
`all` should return an array instead of Capybara::Result

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1271]
Currently `all` returns `Result` instead of array. It has the following downsides:

1. We should delegate all useful methods of `Array` to `@result`. But it's hard to choose all necessary methods. For example currently `reverse` method (that I wanted to use recently at some project) isn't delegated so Capybara user should do `all(locator).to_a.reverse`
2. It increases surface of public API

Before #1246 `all` was used in `assert_selector` and `assert_no_selector` so `Result` was needed. It will be not so after it will be merged. `all` should return an array instead of `Result`

**Comment by twalpole** [comment]
Closing this as returning an Array would prevent us from optimizing the calling of filters on the results
