### ISSUE TITLE
Expose form of app_host actually used by visit as public API

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1369]
It's sometimes useful to check current url of the page. That's why Capybara and Webdriver expose `current_url` method.

When server isn't used user can check that after opening some page current_url is `"#{Capybara.app_host}/path?query#fragment"`.

But when server is used user can't write so easy check as authority is more complicated. So he has to either:

* copy-paste the algorithm used by `visit`
* check not whole url but only scheme, path, query and fragment (it would require to write several lines of code)

IMO both those options aren't good.

Therefore I propose to add read-only `Capybara.actual_app_host` that will return the actual part of url before path that is opened by `visit`. It can be done in 2.5

**Comment by twalpole** [comment]
Closing because I believe the has_current_path matcher with the :url option and a regexp meets this need
