### ISSUE TITLE
Method "#all" collision between Capybara and Rspec

### ISSUE THREAD

**Issue by mhodgson** [jnicklas/capybara#1396]
Unfortunately the `all` method in the Capybara DSL is now conflicting with the `all` matcher in Rspec (https://www.relishapp.com/rspec/rspec-expectations/v/3-1/docs/built-in-matchers/all-matcher). I'm not sure what happens now (fight to the death?), but it did lead to a very confusing error message:

```
The given selector #<RSpec::Matchers::BuiltIn::BePredicate:0x007fd94e726760> is either invalid or does not result in a WebElement. The following error occurred:
       InvalidSelectorError: An invalid or illegal selector was specified
```

Thoughts?

**Comment by schnittchen** [comment]
I have a feature here where I'm not interested in accessing the Capybara method, but RSpec's builtin matcher instead. Worked around with `include RSpec::Matchers.clone`

**Comment by mattwynne** [comment]
Would it be possible to implement a proxy that's intelligent enough to forward methods called on the result of `#all` to either Capybara or RSpec depending on the context?
