### ISSUE TITLE
Save and open path improvement

### ISSUE THREAD

**Issue by NameFILIP** [jnicklas/capybara#1438]
There is a `Capybara.save_and_open_page_path` variable which works if you don't specify a screenshot's filename (`page.save_screenshot`).
But if you call it `page.save_screenshot('somename.png')` it is ignored. It is good when the path is full, but when it's relative that variable is ignored.

For example,
```
Capybara.save_and_open_page_path = 'tmp/capybara'
page.save_screenshot # correct location
page.save_screenshot('somename.png') # project root folder
```
The save_screenshot's implementation: https://github.com/jnicklas/capybara/blob/master/lib/capybara/session.rb#L658

**Comment by xaviershay** [comment]
Maybe renaming to `default_save_and_open_page_path` would make it clearer? I'm not sure switching the behaviour here would be any more intuitive.

**Comment by NameFILIP** [comment]
Why not? I usually don't want to pollute my project directory with a bunch of screenshot files. I prefer a special folder (`tmp` for example) where all the generated files are saved. To achieve this, I set the `Capybara.save_and_open_page_path = 'tmp'`. If you don't need such behaviour - just don't set the variable.

Right now, I have to make sure there is a correct prefix for all `page.save_screenshot('tmp/somename.png')`. That's a little bit annoying.

**Comment by twalpole** [comment]
PR #1676 changes this behavior and makes it more sane
