### ISSUE TITLE
Proposal: Rename default_wait_time to default_max_wait_time

### ISSUE THREAD

**Issue by prpetten** [jnicklas/capybara#1442]
I think its a bit misleading to call it default_wait_time, as it tends to imply that is the wait time in place for every action.  Particularly with the removal of wait_until, and the implicit action of Capybara's matchers to keep retrying until it finds a match, or the default_wait_time is exceeded.  The current naming reads to me that there is a 2 second delay, then the matcher is tried once.  

Obviously this would be something to change in a big release and phase out with deprecation before another big release, but I do think adding 'max' makes the name better.

I won't be at all offended if you reject this idea out of hand.

**Comment by dhulihan** [comment]
Some people visiting the repo may think that `master` reflects the current gem version. For instance, the `default_max_wait_time` section of README might confuse new capybara users. :crying_cat_face:

**Comment by michaelmagistro** [comment]
@dhulihan I'm a baby Capybara and it confused me D:

**Comment by adsteel** [comment]
@dhulihan Same here. That is confusing. May be better to keep the next version in a separate branch, and have master always reflect the current gem verion.

**Comment by twalpole** [comment]
@adsteel That would be counter to the way pretty much every other project organizes itself.  If you want the README for a specific version - look at that versions README, or read the docs for the version you're using on rdoc.info

**Comment by MaxPleaner** [comment]
it's really easy to forget to check the branch list. It's common to have the master branch be stable and use other branches for subsequent development. I think a note in the readme really would help beginners; some other projects are doing this as well.

**Comment by twalpole** [comment]
@MaxPleaner That may be common for an app, but it's not for most gems.  A PR with a note in the readme would be considered as long as it is worded/implemented in a way I don't have to modify/update it for every release
