### ISSUE TITLE
Download File API

### ISSUE THREAD

**Issue by nritholtz** [jnicklas/capybara#1449]
As per https://github.com/thoughtbot/capybara-webkit/issues/691#issuecomment-65437734, I would like to suggest a new API for downloading files using Capybara.

Currently, I use Selenium Firefox with specific Firefox profile settings, to download files from links, to a specific directory. However, I find that I have to swap between Webkit and Selenium too often, that I'd like to be able to use Capybara Webkit exclusively.

Is it possible as per @jferris comment to provide some form of an API from Capybara for downloading files?

**Comment by twalpole** [comment]
Closed due to lack of response

**Comment by abotalov** [comment]
> Currently, I use Selenium Firefox with specific Firefox profile settings, to download files from links, to a specific directory.

We should support not only Firefox driver. Not all Webdriver implementations have the possibility to autosave files. Also they have different API for it. So it's not a good idea to standardize this way to do file downloads at Capybara side.
