### ISSUE TITLE
Proposal for better failure message when "Unable to find field" during form interaction

### ISSUE THREAD

**Issue by Aerlinger** [jnicklas/capybara#1451]
Capybara gives a rather vague and unhelpful "Unable to find field" exception message if an expected form field is missing. Although, it may seem like a trivial issue, the real problem is that this error message masks the root cause of the underlying test/spec failure.  As such, this is a rather common exception due the fact that there are a variety of orthogonal circumstances in which the `Capybara::ElementNotFound` exception can be raised (for instance, maybe it's a 500/404 error message, a simple typo in either the view or the spec, or a different page is rendered than is expected, etc...). Since the root cause of the issue is almost always at a "deeper level" than Capybara, dispatching a more detailed exception description would go a long way in making failing specs easier to trace, debug, and maintain.

I'd propose a simple trace/helper printout of either the raw DOM html, or perhaps a list of the available DOM elements on the page (i.e. something like the printout on the `have_content` matcher). I also suppose there are two minor drawbacks: (1) increased coupling between the exception handling logic and the parsing service, and (2) perhaps a very slight performance overhead when this specific exception. However, I'd personally find this capability very helpful and would be happy to submit a PR if it's something that is thought to be useful.

**Comment by twalpole** [comment]
Closed due to lack of followup
