### ISSUE TITLE
Odd has_css? behaviour?

### ISSUE THREAD

**Issue by ioquatix** [jnicklas/capybara#1454]
We have a test which checks HTML5 form validations. We have a text area which uses `setCustomValidity` which adds the class 'user-error'.

When we write a test like so:

```ruby
			# < character limit
			within("form.basic") do
				fill_in 'details', :with => 'a' * 49
			end
			expect(page).to have_css 'textarea[name=details].user-error'
```

It fails incorrectly.

If immediately before the expect line, I add `binding.pry` and print `page.has_css? 'textarea[name=details].user-error'`, I get the correct result. I thought this might be a synchronisation issue, but no amount of `reload` or `sleep` seems to make the test pass. Any idea what is going wrong?

**Comment by twalpole** [comment]
Sorry for the delay -- depends on your app and what you can do -- as I said previously - clicking on some other element on the page could do it, or any other action on the page that would cause the textarea to lose focus - there is no one correct way
