### ISSUE TITLE
Feature request -- put a method "visit" inside the describe scope to catch for common error of not wrapping your test in "it" block

### ISSUE THREAD

**Issue by jasonfb** [jnicklas/capybara#1456]
This one feature would save thousand and thousand of hours of developer time. See thread below. 

visit must come inside of an it block

describe 'target availability pie chart' do
    it “should load the page” do
 	visit '/'
    	expect(page).to have_content('blah’)	
    end
 end

I do that all the time myself. I do that so often I think it would be really great if there were an “it” method defined inside of the describe scope that just raised an error saying “you didn’t wrap your test inside of an ‘it’ block”

That feature alone would save thousand of hours in developer frustration on this one issue. 

-Jason

On Dec 12, 2014, at 11:58 AM, Nicola Adamchik <nicolaa@gmail.com> wrote:

GEMFILE:

gem 'rails', '4.1.1'

group :development, :test do
  gem 'rspec-rails', '3.0.1'
  gem 'capybara', '2.4.1'
  gem 'capybara-webkit'
end

spec_helper.rb
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'capybara/rspec'
require 'capybara/rails'

RSpec.configure do |config|

  config.include Capybara::DSL

  config.infer_spec_type_from_file_location!
end

spec/features/target_dashboard_spec.rb
require 'spec_helper'

describe 'target dashboard', type: :feature do

  describe 'target availability pie chart' do
    visit '/'
    expect(page).to have_content('blah')
  end
end

-----------------------------------------------------------------------------------------
> bundle exec rspec

undefined method `visit' for RSpec::ExampleGroups

What am i missing?

-- 
You received this message because you are subscribed to the Google Groups "Capybara" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ruby-capybara+unsubscribe@googlegroups.com.
For more options, visit https://groups.google.com/d/optout.

-- 
You received this message because you are subscribed to the Google Groups "Capybara" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ruby-capybara+unsubscribe@googlegroups.com.
For more options, visit https://groups.google.com/d/optout.

**Comment by twalpole** [comment]
This seems more like an rspec issue than a capybara issue -- perhaps a suggestion for rspec to give a better error message when an undefined method is called on an instance of ExampleGroups would be helpful
