### ISSUE TITLE
Problem with send_keys usage

### ISSUE THREAD

**Issue by NameFILIP** [jnicklas/capybara#1459]
When sending a special keys, like arrow keys ("up", "down", "left", "right") there is a different syntax for different drivers

For the selenium's webdriver I use:
```
find('.some-input').native.send_keys('faci', :down, :down, :down, :down, :enter)
```
For the poltergeist:
```
find('.some-input').native.send_keys('faci', :Down, :Down, :Down, :Down, :Enter)
```

The root of this problem is that Selenium keys differ from PhantomJS keys:
https://selenium.googlecode.com/svn/trunk/docs/api/rb/Selenium/WebDriver/Keys.html
https://github.com/ariya/phantomjs/blob/master/src/modules/webpage.js#L465

It would be nice if capybara has some mapping or restrictions for this, so that you can easily switch between different drivers.

**Comment by twalpole** [comment]
@jferris @jonleighton @mhoran  - any thoughts on supporting a unified definition/mapping for special keys?

**Comment by jferris** [comment]
I'd be fine mapping a symbol or constant to a key press, like `send_keys(:down)` or `send_keys(Capybara::KEY::DOWN)`.

**Comment by twalpole** [comment]
@jferris Would you see this being handled in each driver, or having the drivers provide the mapping and #send_keys in their node classes - and capybara doing the translation in Capybara::Node::Element#send_keys ?

**Comment by jferris** [comment]
I think you'd need two mappings:

* The list of normalized key codes mapped to the list of driver-specific key codes
* The strategy for sending one or more key codes to a driver

I'm not sure how much added value there is in having the first mapping. Expecting the drivers to normalize the key codes seem okay to me, but as a driver author, I don't think it would be more difficult for me to implement one approach over the other, so I'm fine with either.

**Comment by abotalov** [comment]
Some my opinions:
1. `Capybara::Node::Element#send_keys` shouldn't map keys (like `:down`, `:shift`, etc.). Mapping should happen at driver side.
2. Constants like `Capybara::KEY::SHIFT` won't be useful for users. Symbols are better.
3. It makes sense to standardize to Selenium keys (http://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/Keys) as they are documented in [draft spec](https://w3c.github.io/webdriver/webdriver-spec.html#widl-WebElement-sendKeys-void-DOMString-value).

@jferris Could you clarify what do you mean by `The strategy for sending one or more key codes to a driver`? Do you mean sending keys with pressed another key or something else?

**Comment by jferris** [comment]
> Could you clarify what do you mean by The strategy for sending one or more key codes to a driver? Do you mean sending keys with pressed another key or something else?

Sorry, by "driver" I meant "native underlying implementation."

Basically, each driver will need to implement `send_keys` no matter what. If `Capybara::Node::Element#send_keys` maps the keys, drivers will also need to implement `map_key` or something similar.

**Comment by twalpole** [comment]
Closing this -- discussion should move to PR #1472
