### ISSUE TITLE
Error compiling CSS asset when run all rspec at first time

### ISSUE THREAD

**Issue by crokobit** [jnicklas/capybara#1462]
Everytime I run all rspec at first time, capybara tests get this error:
"Error compiling CSS asset when run all rspec at first time"
It will all pass at second time running all rspec.
If I run single capybara test, it always pass.

What direction should I find for solving this?
What should I do for solving this?

thanks.
![screen shot 2014-12-30 at 10 11 43 am](https://cloud.githubusercontent.com/assets/4341690/5577637/7b0849ee-9050-11e4-8203-ba11a615a721.png)

**Comment by twalpole** [comment]
Did you find a solution for this -- I'm 99.9% sure this has nothing to do with capybara and is probably an issue with your versions of sprockets/sass/etc.
