### ISSUE TITLE
Add :type option to show which element it is (+ related improvements)

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1463]
I see the following downsides in some aspects of Capybara:

1. `find` always returns instance of `Element`, not a subclass of it. Therefore some methods that make sense only for some kinds of elements aren't provided (e.g. Select#selected_option, FileField#set, Image#loaded?, etc.)
2. :field, :radio_button, etc. are:
  * hard to debug if ElementNotFound occurs. Writer of the code may have meant id/name/placeholder/etc. but it's not easy to find if that element really exists on the DOM
  * difficult to remember which attributes are supported and which are not (is alt attribute supported?)
But people use them as:
  * `have_field('name')` looks better than `have_css("*[name='name']")`
  * there is no good alternative if you want to use selector-specific options.  
    `expect(page).to have_field('field_id', with: 'something')`  
    `expect(page).to have_select('label_text', with_options: ['42', '43'])`

Proposed solution:
1. Add `:name`, `:value`, `:label_text`, `:href`, etc. selector kinds out-of-the-box to make it easier to find elements in a deterministic way without necessity to write longer css/xpath selectors
2. Add `:type` option that specifies which kind of element it is. Examples:

```ruby
have_selector(:id, 'field_id', type: :field) # additional options specific to type: :field are available
have_selector(:field, 'field_id') # type: :field is implicit if selector kind is :field
find(:id, 'field_id', type: :field) # returns a subclass of Capybara::Node::Element, e.g. Capybara::Node::Element::Field
```

New methods `Capybara.register_element_type` and `Capybara.register_selector_kind` will be added. `Capybara.add_selector` will be deprecated. It will be possible to register both element type and selector kind using `add_selector` (some methods will be delegated to registering element type and some others to registering selector kind).

User would be able to define a subclass of `Capybara::Node::Element` and its relation to one of registered element types (some subclasses will be defined as part of Capybara).

`:type` won't be used to check element's tag but only to return element of a more specific class and to support type-specific options (like `:checked`, `:disabled`, `:href`, etc that are defined by `register_element_type`).

This change looks backwards compatible to me. 

WDYT?

**Comment by twalpole** [comment]
Sorry for the delay on this - personal issues have kept me away for a while.
At first glance this sounds interesting, although I think it is two different issues and if implemented should probably be done as two different PRs.  A couple of issue
1. Its not clear to me why add_selector would be deprecated, or what register_selector_kind would be for. 
2. Would you  see this being implemented via changes to the xpath gem, or strictly in capybara.
3. If :type isn't checking elements tags isn't this opening users up to even more difficult to debug issues?

**Comment by abotalov** [comment]
> 1. Its not clear to me why add_selector would be deprecated, or what register_selector_kind would be for.

I played around with code and decided that there's no need to deprecate it. Only element type - related methods (`label`, `filter`, `description`, `describe`) will be deprecated by adding `@deprecated` YARD tag.

> 2. Would you see this being implemented via changes to the xpath gem, or strictly in capybara.

XPath/css selectors needed for `:href` or `:name` are very simple so it doesn't make sense to extract them to xpath gem. If there would be complex enough selectors, probably I'll try to make a change in xpath gem.

> 3. If :type isn't checking elements tags isn't this opening users up to even more difficult to debug issues?

I believe `:element` shouldn't be used for checking element tags as:
1. L&F of HTML element can be significantly changed from standard.
2. It would complicate implementation (we have to merge it into css/xpath selectors)
3. I don't think an idea to merge a tag name into css/xpath selector is a good one. I wouldn't expect Capybara to do it. Probably it makes sense to merge it into selectors like `:id` but I would vote for selectors to be consistent here.
4. That would separate responsibilities of element type and selector.


I have been implementing this feature and there's an issue with behavior of `Capybara.add_selector` if selector/element type with that name was already registered. There are two options:
1. When it's invoked, replace existing Selector with Selector created from supplied block + replace ElementType with created from the supplied block
2. When it's invoked, replace existing Selector with Selector created from supplied block + instance_eval block in scope of existing ElementType

Option 1 will be fully compatible with existing behavior of `add_selector`. But in this case it would be impossible to add selector without not-deregistering element type. Users of 2.x versions will have to invoke `add_selector` prior to `register_element_type`. If `filter`, `label`, etc. will be removed in 3.0 from `Selector`, there will be no need to do anything with ElementType from Selector so there will be no this limitation.

Option 2 will break the following use case:
```ruby
Capybara.add_selector(:beatle) do
  # filter and xpath are invoked here
end
Capybara.add_selector(:beatle) do
  # xpath is invoked here
end
# filter still exists for :beatle element type
```

I would prefer option 1 as limitation will exist only until 3.0. Do you agree?

**Comment by twalpole** [comment]
I have to think about this some more.  I don't understand why we would be deprecating anything for this change.   It seems to me that just adding support for the :type parameter as the class which results should be, and then adding some new predefined selectors (which really is a different issue than this one) produces the same outcome without massive changes, and still keeping the current flexibility for custom selectors?  

As far as calling add_selector twice for the same selector, I would expect it to completely replace the current selector (as I believe it currently does).  Maybe we need to add a Capybara.update_selector or something to allow for changing a selector, or update_selector_type if we really think people will want to be changing the returned element types of the default selectors - of course users could just do something like  Capybara::Selector.all(name).some_method_name = :new_type to change the returned element type too.

**Comment by abotalov** [comment]
> I don't understand why we would be deprecating anything for this change.

I want to give users ability to write:

```ruby
have_selector(:id, 'field_id', element: :field, with: 'contents')
```

To make it possible custom filters like `:with` should be part of ElementType, not Selector. Therefore, I'd like to remove this ability from Selector (in future) so it won't be duplicated in two places. If `:element` isn't supplied, then it's set to `@selector.name`.

**Comment by twalpole** [comment]
So it seems like I didn't understand what you were suggesting in the first place - I don't think moving the "selection" of elements from the selector to element types is helpful, and seems like its going to end up with more duplication than before.  I think

    have_selector(:id, 'field_id', element: :field, with: 'contents')

is going to become highly confusing since with: will no longer have a standard meaning when used with the :id selector.  A user will now also have to add a new ElementType for ever selector type they add.  This seems to add layers of complexity for few if any benefits.  I get the desire for being able to change the type of the returned element, but I don't get what benefit the rest of these changes bring that couldn't just be done with a custom selector.  I'll go look at the PR you just pushed, but as of now I'm not leaning towards this.  If you really need to be able to call random methods on the element type couldn't that just be done with a filter  

    have_selector(:id, 'field_id', element: :field, call_on_element({with: 'content'}))

or something - while still maintaining the current flexibility  (obviously call_on_element is a terrible name for the filter, but something along those lines)

**Comment by twalpole** [comment]
I guess maybe my real issue with this is that this is really multiple issues that have been intertwined,  I think I read at least 3 things you're trying to change -
1.  Being able to return instances of a subclass of Element for given selectors
2. Being able to have sets of filters that can be specified for use with any selector (and hopefully allowing for a default set for any given selector)
3.  Add new selectors out of the box

Is that correct?

**Comment by twalpole** [comment]
@abotalov  for # 2 in my list of what I think you're looking for - please take a look at the filter_set branch I just pushed - I think something along those lines would provide the functionality you're looking for without requiring deprecation of a bunch of things, although its just a first stab at it and I may need to spend a bit more time thinking things through

**Comment by abotalov** [comment]
I haven't responded previously as I got some concerns whether this feature has a value at all.

I don't see much value in using `:type` without any wrapper. It's just some additional code and I would like to use it via some sugar placed on top of it (the sugar might be not a part of Capybara, though).

Consider this example (with sugar):
```ruby
class LoginPage < BasePage
  field :username_field, :id, 'field_id'
end

login_page = LoginPage.new
expect(login_page).to have_field('field_id') # capybara matcher
expect(login_page).to have_username_field # matcher provided via method_missing, equivalent to have_selector(:id, 'field_id', type: :field)
```
The fact that `field` and `have_field` take inconsistent parameters doesn't look consistent, unfortunately.

**Comment by onebree** [comment]
Would this solve my problem?

I want to show that the "selected" option for a select element is "Extension". With my current knowledge of Capybara, I cannot do this with simply `page.has_field?("Key type", with: "Extension")`, because the resultant "match" contains all options.... Not looking for the CSS for the one selected.

**Comment by twalpole** [comment]
@onebree Please ask how do I do things type questions on the mailing list as requested in the README -  or read the docs and look for has_select? with the :selected option

**Comment by onebree** [comment]
@twalpole thank you, that helps. I thought the item was a field.

**Comment by twalpole** [comment]
I added the reusable sets of filters as PR #1679 so thoughts about it can be added there.  I believe the rest of this was determined to probably not be useful so I'm closing it.  If it is still considered useful we can reopen
