### ISSUE TITLE
I would like the option to not create the default html file for cucumber

### ISSUE THREAD

**Issue by scalixte-mdsol** [jnicklas/capybara#1464]
When running tests with cucumber with automated save on failure, both the image an a corresponding html file are saved. However, I would like the options:
1) Save Image only (no HTML)
2) Embed Image into HTML (No Image file)
3) Embed Image into HTML (with Image file)

**Comment by twalpole** [comment]
This isn't functionality provided by Capybara, so I assume you are using the capybara-screenshot gem and your request belongs over there.

**Comment by scalixte-mdsol** [comment]
Please disregard the issue written earlier. Thanks, @twalpole .
