### ISSUE TITLE
How to fix 414 Error (request uri is too long) when using DataTables which works in all major browsers

### ISSUE THREAD

**Issue by TrevorHinesley** [jnicklas/capybara#1467]
This works fine when testing manually, but using Capybara with a JS driver (such as Selenium Webdriver), it stalls out because the GET request is too large. Switching the index route to a POST allows this to work, but is not RESTful (a POST to /resources should create an object, not return an index, that's what GET at /resources is for). And again, it works in normal browsers.

**Comment by twalpole** [comment]
How long is your uri?  Different browsers have different limits as do different servers -  Capybara starts up the rails app using WEBrick which IIRC has a limit around 2048, for url length, to match some version of IEs limit - I believe you can change WEBricks default limit (check the WEBrick docs for that), but using a URL anywhere near a browsers or servers length limit is not a great idea - maybe your routing scheme needs a rethink

**Comment by TrevorHinesley** [comment]
I'm not using any special routing, this is a DataTables default which is used on thousands of sites. I could change it to a POST but that seems to defy convention. Works fine in Thin, which is what my Rails app uses.

**Comment by TrevorHinesley** [comment]
Switched Capybara's server to Thin, resolved.

**Comment by JoeZ99** [comment]
another option is
https://github.com/raggi/capybara-puma

**Comment by synth** [comment]
How did you switch capybara's server to thin? Also, the capybara-puma gem is now deprecated saying capybara has "native features". How can we increase the max uri length for get requests and do so in a portable way(eg so it can run remote CI like Travis)?

**Comment by twalpole** [comment]
@synth capybara-puma is now deprecated because you can just do `Capybara.server = :puma` with recent versions of Capybara.  To switch to thin you'd need to use Capybara.register_server to setup thin, and then after that specify `Capybara.server = :thin`  - see https://github.com/jnicklas/capybara/blob/master/lib/capybara.rb#L481 for how puma is registered as an example

**Comment by synth** [comment]
👍 Thanks!

**Comment by ashish91** [comment]
I fixed by adding:

```
Capybara.server do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, :Port => port)
end
```

**Comment by twalpole** [comment]
@ashish91 How old is the Capybara you are using?  The code you show should give a deprecation warning -- use `Capybara.register_server` to register a named server and then specify that one.  See the answer above.

**Comment by ashish91** [comment]
@twalpole I am using capybara 2.13.

**Comment by twalpole** [comment]
@ashish91 And that's not outputting a deprecation warning???  It definitely should be.

**Comment by ashish91** [comment]
Yes I get `DEPRECATED: Passing a block to Capybara::server is deprecated, please use Capybara::register_server instead`

**Comment by choosen** [comment]
Add in initializer (selenium.rb):

```ruby
 Capybara.register_server(:thin) do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, Port: port)
end
```

And set in spec config: 
`Capybara.server = :thin`

**Comment by choosen** [comment]
But I suggest to choose :puma  
-> It is getting more updates for now and you do not need to register with above method

**Comment by ashish91** [comment]
Thanks @choosen It also works with `puma`:

```
Capybara.register_server :puma do |app, port, host|
  require 'rack/handler/puma'
  Rack::Handler::Puma.run(app, Port: port, Host: host, Threads: "0:4")
end
Capybara.server = :puma
```

**Comment by twalpole** [comment]
@ashish91 Capybara has already registered a :puma server, so you don’t need to do the register_server call. Additionally if you do register it the way you show you won’t be able to Ctrl-c stop your tests
