### ISSUE TITLE
Capybara issue inside a within block 

### ISSUE THREAD

**Issue by hassanabbas901** [jnicklas/capybara#1468]
require "spec_helper"

require "rails_helper"

include Capybara::RSpecMatchers

include Capybara::DSL

Capybara.javascript_driver = :webkit

feature "Course", :type => :feature do

scenario "Get index and apply different search filters for course types", js: true do

visit "/courses"

within("//body") do

find(:xpath, "//input[@id='course_type_id_1']").click

find(:xpath, "//div[@class='course-right-sec']")

expect(page).to have_content('65,171 courses')

expect(page).to have_content('Fundamentals of Design')

end

end

end

The problem i am facing with the above code is that when i find a specific div with a respective class inside a within block, whether the div with that class exists or not, the test passes in any case. Any help on this issue?

**Comment by abotalov** [comment]
https://github.com/jnicklas/capybara#beware-the-xpath--trap
