### ISSUE TITLE
Wait between user actions

### ISSUE THREAD

**Issue by NameFILIP** [jnicklas/capybara#1475]
I have some troubles with the speed of capybara checks. Sometimes, it clicks too fast. User doesn't do different actions every `0.05` seconds. 

For example, I click to open modal window, enter some data and click save. Capybara does all this when the modal is only starting to show up. The javascript execution is still in progress and Save button handler is not yet attached. I have to add `sleep 1` or `2` between actions to finish JS execution. 

The main idea is: we try to imitate a user, and he usually does little pauses between actions. It would be useful to have a parameter, like `Capybara.wait_between_actions` or something similar.

**Comment by twalpole** [comment]
For actions that need changes to have happened first, you should be testing for those changes to exist first (classes set/removed on modal when it's fully opened, etc) or disable animations in test mode.  Adding delays between every action would make tests unbearably slow. If you need more info please ask questions on the mailing list as mentioned in the README

**Comment by NameFILIP** [comment]
Sure I do test that changes exist. The problem is when you test a more or less complex Single Page Application, you very often have to dig into the javascript code trying to figure out what happens exactly before what you need. Just think maybe there is a better way to overcome this problem..

How to disable animations in test mode? (I've found this solution http://stackoverflow.com/questions/11131875/what-is-the-cleanest-way-to-disable-css-transition-effects-temporarily#answer-11132887) or is there a parameter somewhere? Or maybe it's somehow possible to determine if JS is still executing?

**Comment by twalpole** [comment]
all depends on how you're doing the animations, but again - ask questions on the mailing list not in issues
