### ISSUE TITLE
Multiple Capybara Servers

### ISSUE THREAD

**Issue by tonywok** [jnicklas/capybara#1476]
Currently there doesn't seem to be a way to have capybara switch "servers" between tests?

For example, can we use the following configuration for a group of specs

```
Capybara.server do |app, port|
  require 'rack/handlers/thin'
  Rack::Handler::Thin.run(app, :Port => port)
end
```

And use the default server (webrick I believe) for the remaining?

**Comment by twalpole** [comment]
As requested in the README, please ask questions about how to use Capybara on the mailing list
