### ISSUE TITLE
Select multiple not working.

### ISSUE THREAD

**Issue by theonegri** [jnicklas/capybara#1479]
So, I have the following select:
```
<select size="3" multiple="multiple" js_required_field="Class Level" id="dnf_class_values_job__class_level___" name="dnf_class_values[job][class_level][]">
<option value="274" selected="selected">UCLA Extension Certificate</option>
<option value="230" selected="selected">First Year</option>
<option value="231" selected="selected">Sophomore</option>
<option value="232" selected="selected">Junior</option>
<option value="273">Senior: 4th Year</option>
<option value="233">Senior: 5th Year</option>
<option value="234">Master's</option>
<option value="235">Doctoral</option>
<option value="237">Alumni</option>
<option value="236">Post-Doctoral</option>
</select>
```

And I do:
```
select('Junior', :from => 'dnf_class_values[job][class_level][]')
select('Sophomore', :from => 'dnf_class_values[job][class_level][]')
```

But it only select the last one not both of them.

Here is some of the config I have:
```
Capybara.register_driver :selenium_chrome do |app|
      Capybara::Selenium::Driver.new(app, :browser => :chrome)
    end
    Capybara.current_driver = :selenium_chrome
    Capybara.javascript_driver = :selenium_chrome
```

**Comment by twalpole** [comment]
There are tests for this exact behavior so I'm going to start by assuming this is not actually an issue in Capybara.  What #select does is: find the element and then click on the option - assuming its not already selected.  In your case the select box already has the two entries selected so the two select method calls should do nothing.  Do you happen to be using some kind of javascript select box enhancement that is changing the page structure?

**Comment by theonegri** [comment]
Not that I know.
I try with a simple example:
```
Capybara.register_driver :selenium_chrome do |app|
      Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
Capybara.current_driver = :selenium_chrome
Capybara.javascript_driver = :selenium_chrome
Capybara.app_host = 'http://www.w3schools.com'
Capybara.run_server = false # don't start Rack
visit '/tags/tryhtml_select_multiple.htm'
select('Volvo', :from => "cars")
select('Saab', :from => "cars")
```
And in the chrome launched, I only see this: http://cl.ly/image/3w1p1x3r0t3W

So I'm assuming that chrome doesn't display both select? Or am I doing something wrong?

**Comment by twalpole** [comment]
What version of chrome and chromedriver are you using?

**Comment by theonegri** [comment]
Version 40.0.2214.94 (64-bit) on OS X 10.10.2

**Comment by twalpole** [comment]
and chromedriver?

**Comment by twalpole** [comment]
If you're not running chromedriver 2.14 - trying upgrading that, and if that doesn't fix your issue, maybe try asking over on the mailing list -- works fine for me.

**Comment by theonegri** [comment]
Sorry, forgot that part.
I was using ChromeDriver 2.10.267517 and I just updated to the latest version.

I works perfectly.

Thanks a lot for your time!
