### ISSUE TITLE
JS upload file cannot get file from attach_file, or find(..).set

### ISSUE THREAD

**Issue by evandavid** [jnicklas/capybara#1483]
Hi, please help me with this
I have application that have ability to upload file from JS

I collect the file use this code

data = new FormData();
data.append('file' $("#file_input")[0].files[0])

but when I do testing using capybara
attach_file 'fieldname', filepath
or
find(..).set filepath

JS didnt recognize file and send undefined into server
Thank you :)

**Comment by twalpole** [comment]
Please ask howto questions on the mailing list as requested in the README
