### ISSUE TITLE
I can't choose a radio button with a button-group from bootstrap

### ISSUE THREAD

**Issue by carlqt** [jnicklas/capybara#1484]
The title says it all. It seems that when I do `choose "radio_button_true"` for my specs, it just highlights the radio button but fails to choose it. 

Here's the bootstrap feature I'm talking about
http://getbootstrap.com/javascript/#buttons-checkbox-radio

If you wan't a clearer description, I created a repository that demo's this error
git@github.com:carlqt/capybara_issue.git

Just type in `rspec` then watch how it fails.

**Comment by twalpole** [comment]
This is an issue with how the bootstrap javascript works for button-groups -  it needs the label to be clicked on rather than the radio button.   In this case that could be done with something like   

    find(:label, text: 'Yes').click

or as something that could be turned into a  choose_bootstrap helper or something

    find(:radio_button, 'human_male_true').find(:xpath, './ancestor::label').click
