### ISSUE TITLE
API docs refer to Capybara::Element not Capybara::Node::Element

### ISSUE THREAD

**Issue by eoinkelly** [jnicklas/capybara#1485]
Very minor thing but the API docs refer to `Capybara::Element` which does not exist e.g. https://github.com/jnicklas/capybara/blob/master/lib/capybara/node/finders.rb#L25 - I presume they should refer to `Capybara::Node::Element`?

**Comment by twalpole** [comment]
Technically in the location referenced it could be Capybara::Node::Element or Capybara::Node::Simple I believe, but yes it is incorrect -  PR would be welcome
