### ISSUE TITLE
input element  label to find 

### ISSUE THREAD

**Issue by rails-geek** [jnicklas/capybara#1489]
Not able to find input element label using capyabra. Is there any default finder can give the label for the input element?
for eg:
``` javascript
<form id="f" onsubmit="return secform_confirmSubmit();"  action="flow.jsf" method="post">
   <table>
      <tbody>
         <tr>
            <td class="custom-form-columns">
               <span id="fc4" >
               <label id="et" title="The field "First Name" is mandatory.">
               <input id="et"  type="text" value="" autocomplete="off" >
              <label id="et" title="The field "Last Name" is mandatory.">
               <input id="et"  type="text" value="" autocomplete="off" >
               <span id="et"> </span>
               </span>
            </td>
         </tr>
      </tbody>
   </table>
</form>
```
> page.all("form").first.find.all("input").first.find(:xpath, "..")
this returns > #<Capybara::Element tag="td">

Is there any way to get label element of the input or input before element using capyabara.

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README.  Also, you'll probably want to clean up that html to be valid before reposting the question on the mailing list (can't have three elements with the same id of "et", and the label should either surround the input or have a for attribute linking it to an input)
