### ISSUE TITLE
assets precompile failing after adding capybara gem to Gemfile

### ISSUE THREAD

**Issue by keshavkuruva** [jnicklas/capybara#1490]
Added capybara gem along with selenium web driver to Gemfile. rake assets precompile is breaking since then. Tracing the issue seems to point the problem at this place.

/Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:199:in `block in non_options': file not found: assets:precompile:all (ArgumentError)
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:178:in `map!'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:178:in `non_options'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:237:in `non_options'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:58:in `process_args'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/minitest/unit.rb:1073:in `_run'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:27:in `run'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:780:in `run'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
	from /Users/keshav/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'

Appreciate your help, 
Keshav.

**Comment by twalpole** [comment]
Capybara has nothing to do with asset compilation and isn't listed at all in the stack trace you posted, so I'm 99.9% sure it has nothing to do with this error.   You might want to look at anything else that was changed at the same time as you added capybara.  You might also want to post the mailing list mentioned at the top of the readme to see if anyone there has had a similar issue.

**Comment by keshavkuruva** [comment]
Thanks Guys. Fixed this. Was being caused because of a different gem called contest that was being used along with capybara. I was able to fix this after setting require => false for contest gem in Gemfile.
