### ISSUE TITLE
click_link has an error when href is javascript:void(0)

### ISSUE THREAD

**Issue by DotHide** [jnicklas/capybara#1491]
if I set `href` to '#', the test case is ok!
```
<%= link_to 'appoint', '#', :id => 'program1', :onclick => 'alert(ok);' %>
```

but when I change `href` to `javascript:void(0)`, then I run test again, It'll give me a error
```
NoMethodError: undefined method `empty?` for nil:NilClass
```

**Comment by twalpole** [comment]
What driver are you using? Please show the stack trace for the error.

**Comment by twalpole** [comment]
Since no further info has been provide, I am assuming this was while using the racktest driver - and am fixing it for that case -- If it was not using the racktest driver you will need to provide the info requested.
