### ISSUE TITLE
Window#maximize spec fails when running on Travis

### ISSUE THREAD

**Issue by twalpole** [jnicklas/capybara#1493]
The window#maximize spec has recently stopped passing on Travis runs

**Comment by twalpole** [comment]
@abotalov You did a great job getting this passing originally with the awesome window manager.  Any chance you have time to look at it again and see if you can figure out what has changed that is causing it to fail with firefox every time (I believe it passes with chrome).  I have marked the test as pending for the firefox/travis combo currently.

**Comment by abotalov** [comment]
I reproduced it on my machine. This test passes with FF + awesome + Xvfb + selenium 2.44.0 /  2.45.0.dev2 / 2.45.0.dev2 but fails with selenium 2.45.0.dev / 2.45.0

I don't yet what is the cause of it.

**Comment by twalpole** [comment]
This could be caused by the significant performance degradation the firefox driver has in selenium 2.45.0  hopefully 2.45.1 or 2.46 will be released soon with the fix so we can confirm.   https://code.google.com/p/selenium/issues/detail?id=8551
