### ISSUE TITLE
attach_file working with (js: true) broken with phantomjs, but works in phantomjs192

### ISSUE THREAD

**Issue by lewang** [jnicklas/capybara#1494]
#1483 was the last mention I saw of this from someone.

On Mac, I upgraded to phantomjs 2.0 using homebrew and immediately couldn't attach a file in test cases that required :js.  It's working without js: true.

Downgrading to "phantomjs192" resolved the issue.

**Comment by twalpole** [comment]
The capybara project doesnt support phantomjs itself.  The support is provided via the poltergeist driver, so this issue should be filed with the poltergeist project

**Comment by lewang** [comment]
thnaks.

On Tue, Mar 17, 2015 at 5:43 PM, Thomas Walpole <notifications@github.com>
wrote:

> The capybara project doesnt support phantomjs itself. The support is
> provided via the poltergeist driver, so this issue should be filed with the
> poltergeist project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnicklas/capybara/issues/1494#issuecomment-82610470>.
>



-- 
Le
