### ISSUE TITLE
Unable to reliably get textarea value

### ISSUE THREAD

**Issue by BM5k** [jnicklas/capybara#1497]
Contrived example

The spec
```
fill_in “my_text”, with: ‘A value’
should have_css 'textarea#my_text', text: 'A value'
```
fails

throw in a `binding.pry` and 

```
> find('textarea#my_text').value
=> "A value"
> has_css? 'textarea#my_text', text: 'A value'
=> false
> find('textarea#my_text’).text
=> ""
```

Using `find(‘textarea#my_text').value.should == ‘A value’` works in this rather contrived example, however this does _not_ work if the text area contents are set via ajax. In that case `find('textarea#my_text').value` always returns `””`. (I assume this is because whatever magic that `has_css?` does to auto-wait for javascript to finish doesn’t happen with `find`, but I’m not sure.)

Is this the expected behavior? Is there a workaround for what I’m trying to accomplish?

Versions:
ruby 2.2.0p0
capybara 2.4.4
rails 4.2.1
rspec-rails 3.2.1
poltergeist 1.6.0 + phantomjs 1.9.8

**Comment by twalpole** [comment]
Please ask howto questions in the Google group as requested in the readme

**Comment by BM5k** [comment]
Does that mean this _is_ the expected behavior?

**Comment by twalpole** [comment]
You are using the incorrect methods for what you're trying to do.  Either ask on the mailing (Google groups) list as requested in the README or read the docs further

**Comment by BM5k** [comment]
Thanks for the clarification.
