### ISSUE TITLE
Selenium driver needs to support whitelisting URLs

### ISSUE THREAD

**Issue by twalpole** [jnicklas/capybara#1508]
We need to add the ability to whitelist URLs when using the selenium driver.  99% sure this will require implementing/using a proxy

**Comment by abotalov** [comment]
A proxy (in testing context) is useful for many things, at least for:
* showing requests that come through it (e.g. to check that correct requests are sent to some 3rd party service)
* url whitelisting / blacklisting (e.g. to speedup tests)
* limiting network bandwidth (e.g. to check work of an app in such network conditions)
* injecting HTTP headers into requests (e.g. basic authentication header)
* waiting till a particular response will be received (e.g. if receiving of a response doesn't result in a DOM change but the test, nevertheless, can't proceed without response being received)

A larger number of things is listed here - https://github.com/lightbody/browsermob-proxy. I think those things are also needed as Browsermob is primarily used for testing purposes.

I don't think it makes sense to even start reimplementing this as part of Capybara. If Browsermob has some unsolvable downsides, then it's better to use other gem / modify existing gem / write a new one.

**Comment by twalpole** [comment]
I agree completely, I would much rather have this done using an existing proxy if at all possible

**Comment by abotalov** [comment]
It's possible using https://github.com/jarib/browsermob-proxy-rb (I haven't used it for 9 months though)

**Comment by twalpole** [comment]
Yeah, I have it mostly working

**Comment by twalpole** [comment]
@mhoran @jferris @route @jonleighton I'm working on adding whitelisting of urls to the selenium driver using browsermob_proxy - and was wondering whether the proxy is something that would be of use to other drivers, or to just hide it all inside the selenium driver - feedback appreciated

**Comment by jferris** [comment]
I think what we've built into capybara-webkit already works pretty well in the driver. I'm not sure if it would be less work to integrate it with a proxy. I'm guessing that, if you hide it within the Selenium driver, it will decrease the surface area of public code you have to worry about, which is probably worth keeping it internal.

**Comment by route** [comment]
We've implemented blacklisting in poltergeist in a different way either with native PhantomJS API. While proxy is a good thing in common for all drivers for this specific task I think it's good to hide it.

**Comment by twalpole** [comment]
This is supported through the puffing-billy - maybe add some info to the README about it.

**Comment by twalpole** [comment]
Closing this - puffing-billy is satisfactory for now
