### ISSUE TITLE
have_link's :href option should accept RegEx

### ISSUE THREAD

**Issue by YSavir** [jnicklas/capybara#1510]
I've been trying to use `have_link` and test its `href` attribute using RegEx but to no avail. Here's a sample of the code:

```
scenario { should have_link 'Edit', :href => /\/todos\/\d+\/edit/ }
=> RSpec::Expectations::ExpectationNotMetError: expected to find link "Edit" with href /\/todos\/\d+\/edit/ but there were no matches. Also found "Edit", which matched the selector but not all filters.
```

It'll work with a string, but not with Regex:

```
scenario { should have_link 'Edit', :href => '/todos/7/edit' }
=> true
```

```
scenario { should have_link 'Edit', :href => /#{Regexp.escape('/todos/7/edit')}/ }
=> RSpec::Expectations::ExpectationNotMetError: expected to find link "Edit" with href /\/todos\/7\/edit/ but there were no matches. Also found "Edit", which matched the selector but not all filters.
```

**Comment by twalpole** [comment]
Correct - have_link doesn't accept regex for the :href option, nor is it documented anywhere to. From the docs for click_link which uses the same selector as have_link - 

# @option options [String] :href    The value the href attribute must equal

If instead you're saying you would like to see this functionality expanded to allow for using regexps then fully tested PRs are always considered.

**Comment by YSavir** [comment]
On it, thanks!

Also, was browsing through the tests, and as far as I can tell there isn't any test coverage for the `:href` option to begin with. Is that right?

**Comment by twalpole** [comment]
yes there is in lib/capybara/spec/session/has_link_spec.rb  -- Unlike most projects most of the specs are in the lib/capybara/spec directory because they need to be accessible to all the other drivers that are written for Capybara
