### ISSUE TITLE
attach_file fails in safari

### ISSUE THREAD

**Issue by chris1248** [jnicklas/capybara#1511]
We are starting to include safari (on OSX) in our automated test runs. We currently run our automated tests on firefox and chrome mainly. But Safari poses some problems:

*attach_file* doesn't work.

Specifically I call this code:

    example "I can import Learners into a Course." do
      click_on "Add via CSV"
      expect(page).to have_content("Add Learners to Course with Imports")
      attach_file ("or choose a file", Rails.root.join("spec/support/users.csv"))
      expect(find("h1")).to have_content("Update and Add Learners")
      bla bla bla

It works great when I test it manually. But not capybara!

As you know, capybara implements attach_file here:
/Users/me/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/actions.rb
(line 148)

      def attach_file(locator, path, options={})
        Array(path).each do |p|
          raise Capybara::FileNotFound, "cannot attach file, #{p} does not exist" unless File.exist?(p.to_s)
        end
        find_field(locator, options = {}).set(path)
        #find(:file_field, locator, options).set(path)
      end

Again this code works great in chrome and firefox, but not safari.

Here is the DOM it's attempting to locate (as rendered by 3 different browsers):

```HTML
<!-- Safari -->
<label id="ember1453" class="ember-view file-input blue" for="ember1453-input">
	<input id="ember1453-input" class="ember-view ember-text-field" tabindex="-1" type="file">
	<button class="file-input__button">or choose a file</button>
</label>

<!-- firefox -->
<label for="ember1455-input" class="ember-view file-input blue" id="ember1455">
	<input accept="acceptedFileType" tabindex="-1" id="fileInputId" type="file"></input>
	<button class="file-input__button">or choose a file</button>
</label>

<!-- chrome -->
<label id="ember1453" class="ember-view file-input blue" for="ember1453-input">
	<input type="file" accept="acceptedFileType" tabindex="-1" id="fileInputId">
	<button class="file-input__button">or choose a file</button>
</label>
```

**Comment by twalpole** [comment]
You need to take this up with selenium -  It's not supported there, so there's nothing we can do about it - https://code.google.com/p/selenium/issues/detail?id=4220
