### ISSUE TITLE
Proposal: default_minimum_matches setting

### ISSUE THREAD

**Issue by almostwhitehat** [jnicklas/capybara#1514]
Currently #all will immediately return 0 unless one of the count options are passed to it.

In my own tests, I have found that I almost always need this to be a minimum of 1 (thus the default waits will wait for at least 1) and only in exceptional cases did I want it to be 0. I would like to propose a default_minimum_matches setting, so this can be set globally, and overridden in exceptional places.

I've already implemented this in [my own fork and branch](https://github.com/almostwhitehat/capybara/tree/feature/default-minimum-matches), but I don't know rspec well enough to write the tests needed for a pull request. If you guys like the idea though, and someone wouldn't mind helping with the tests, I'd be glad to submit a PR to get it started.

**Comment by twalpole** [comment]
I'm not convinced having a setting that allows for any number to be default minimum matches is a good idea since it could make for difficult to understand tests.  In most of the cases where you are using #all do you really need #all or are you only using the first result and therefore would be better off with #first?

**Comment by almostwhitehat** [comment]
In my own experience, any time I am using #all it's because I expect there to be at least one result. When I only want the first, I use #first which already waits, after

**Comment by almostwhitehat** [comment]
In my own experience, whenever I use #all I expect there to be at least one result. If I'm not sure if there will be any, then I'm doing a check for the presence, instead of just getting #all and checking for an empty set. When I need the first result, I always use #first instead of #all and grabbing the first result.

Personally, I think my proposed Capybara.default_minimum_matches is more consistent than Capybara.first_default_waiting added in #1506 since this applies to both matchers.

**Comment by twalpole** [comment]
The reason for the setting for #first is that a good argument can be made that a minimum of 1 makes sense when you ask for  the first element and its easy to understand when reading a test that first would probably wait for at least one like #find -   That argument doesn't really hold for #all - and being able to set #all to by default wait for 5 elements makes for tests that cannot be understood by a new person reading them.  This is a no for right now.

**Comment by almostwhitehat** [comment]
I definitely agree - a default wait for 5 elements could be confusing to a new person.

However, I've also seen many users confused by the fact that #find will use the default wait time before returning the element or ElementNotFound - but #all will immediately return an empty array.

Perhaps we're just looking at these wrong, but my thought was that #find and #all should be function the same, except one returns a single match, and the other returns many.

**Comment by twalpole** [comment]
#find returns a single match but #all returns none, 1, or many    -   I think you're really looking for a #one_or_more method - which you could easily add to your test suite without the need to add a potentially confusing setting that have the potential of making tests harder to read for others, and without making them brittle when someone decides to change the setting back to 0, or up it to 3
