### ISSUE TITLE
click_on ArgumentError Exception: wrong number of arguments (2 for 1) Rails 4.2.1

### ISSUE THREAD

**Issue by stevepm** [jnicklas/capybara#1515]
Hi, 

I'm having trouble with the latest version of Capybara (working with Cucumber). 

I am unable to use find or click_on. It will product the following output

`(byebug) click_on("Log in")
*** ArgumentError Exception: wrong number of arguments (2 for 1)

nil
(byebug) click_on
*** ArgumentError Exception: wrong number of arguments (0 for 1..2)

nil
(byebug) click_on("test", "test")
*** ArgumentError Exception: wrong number of arguments (2 for 1)

nil`

I'm using the latest versions of Capybara in my gemfile

Edit:
Versions below:

capybara (2.4.4)
cucumber (1.3.19)
cucumber-rails (1.4.2)
rails (4.2.1)
xpath (2.0.0)

**Comment by twalpole** [comment]
The odds of this being an issue in Capybara are 0.01% or everyone would be complaining.  Therefore please ask in the mailing group as requested in the README rather than creating issues.
