### ISSUE TITLE
visit method error

### ISSUE THREAD

**Issue by tasssik** [jnicklas/capybara#1517]
Hi. And please sorry for my english :)

I study rails with Michael Hartl's Rails Tutorial (2rd edition).

When I wrote 
``` ruby
  describe "About page" do
    
    it "should have the content 'About Us'" do
    	visit '/static_pages/about'
    	expect(page).to have_content('About Us')
    end
  end
```
in my spec file and ran it I got green test, but I expected red, because **I don't have about action** in my Static Pages controller.
Is it ok?

I used capybara 2.4.4, rails 4.2.1, rspec 3.2.1.

**Comment by twalpole** [comment]
Please ask questions on the mailing list as requested in the README
