### ISSUE TITLE
Using expectations in the DSL based on arbitraty code

### ISSUE THREAD

**Issue by cpg** [jnicklas/capybara#1520]
This is more of a question/advice around the Capybara DSL.

We have an interesting testing situation at Amahi where we install web apps and test them with Capybara, however, we found that in some cases, we'd like to pass/fail tests on some internal state of the web app. Is it possible to do that in the current Capybara DSL?

Imagine an app like Webmin or some downloader or similar that has some side effect in the system like adding a file somewhere or something like that. I would like to be able to say in our tests:

```ruby
file_should_exist("/foo/bar")
```

where that helper method is this:

```ruby
def file_should_exist(fname)
   expect(File.exist? filename).to eq(true)
end
```

However, that does not work, because expect complains it should be used in an Rspec test "it" statement.

I may well be not be completely aware of the ins and outs of what I am doing, but we have all things working with Capybara and very happy about that, we just need to be able to fail tests due to some side effects of the web app we're testing.

Thanks!

**Comment by twalpole** [comment]
Please ask questions on the mailing list as requested in the README

**Comment by cpg** [comment]
Done. Ma bad. I must have browsed the README like 1000 times, but usually just go quickly to the DSL.
