### ISSUE TITLE
Element not found

### ISSUE THREAD

**Issue by jstriebel** [jnicklas/capybara#1521]
Hello,

While debugging an RSpec-Test using Capybara I tried to get an element by its ID. I can see it in the body, but Capybara does not find it. I think it should. Here is the output:

    [1] pry(#<RSpec::ExampleGroups::EditProfileGeneralData>)> find '#edit_buyer_1'
    => #<Capybara::Element tag="form">
    [2] pry(#<RSpec::ExampleGroups::EditProfileGeneralData>)> find_by_id 'buyer_title'
    Capybara::ElementNotFound: Unable to find id "buyer_title"
    from /home/aureso/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
    [3] pry(#<RSpec::ExampleGroups::EditProfileGeneralData>)> find '#buyer_title'
    Capybara::ElementNotFound: Unable to find css "#buyer_title"
    [4] pry(#<RSpec::ExampleGroups::EditProfileGeneralData>)> puts page.body.match /.*buyer_title.*/
    <div class="form-group select optional buyer_title"><label class="select optional col-sm-4 control-label" for="buyer_title">Title</label><div class="col-sm-8"><select class="select optional selectpicker form-control" name="buyer[title]" id="buyer_title" style="display: none; "><option value=""></option>
    => nil

Info:

    $ ruby --version
    ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
    $ rails --version
    Rails 4.2.0
    $ gem list capybara
    
    *** LOCAL GEMS ***
    
    capybara (2.4.4)
    capybara-webkit (1.3.1) 

Did I miss something here? Or is this a bug? BR, Jonathan

**Comment by twalpole** [comment]
Yes - you missed the "display: none" on the element - In the future please post questions about how to use Capybara on the mailing list as requested in the README -- The github issues are for confirmed bugs in Capybara
