### ISSUE TITLE
Window#size with for selenium with chromedriver returns larger than expected

### ISSUE THREAD

**Issue by twalpole** [jnicklas/capybara#1522]
On travis using Window#size with selenium and chrome returns a size larger than [window.outerWidth, window.outerHeight], by 1 or 2 pixels in both directions.  Not sure why - needs more investigation

**Comment by RezaRahmati** [comment]
I have same issue, setting size , and I get screenshot, the image size is different on server and my mahcine, do you find any workaround or fix for that?

**Comment by twalpole** [comment]
@RezaRahmati Nope -- I'm guessing it has to do with the window manager being used.  Also on some systems there is a delay between changing the window size and it actually changing, so if you're getting a screenshot immediately after changing the size you may wait to add a slightly delay.

**Comment by twalpole** [comment]
Not much we can do about this, I'm assuming its a rounding issue. Closing
