### ISSUE TITLE
Running rspec from rails controller

### ISSUE THREAD

**Issue by noahjerreel** [jnicklas/capybara#1529]
Hello guys,

Is it possible to run rspec from rails controller (eg. Kernel.system "rspec spec/features/test.rb")?

I tried to run rspec from linux and it's working fine but when I ran it using the controller, it tells unable to connect to firefox. See the screenshot below: 

![image](https://cloud.githubusercontent.com/assets/3905566/7980180/005cdfb8-0ad8-11e5-82a9-773cd991c86c.png)

Thanks!

**Comment by twalpole** [comment]
Ask "how to use capybara" questions on the mailing list as requested in the README
