### ISSUE TITLE
Element not found using click_button

### ISSUE THREAD

**Issue by sivagollapalli** [jnicklas/capybara#1530]
Hi 

I am using capybara as our acceptance framework. But when I do `click_button`, certain times it does click, certain times it throws `Capybara::ElementNotFound:` on my rspec test suite. Is there way to fix this issue permanently?

**Comment by twalpole** [comment]
Ask "how to use capybara" questions on the mailing list as requested in the Readme - and when doing so you'll need to provide more info than this.
