### ISSUE TITLE
Select action doesn't respect disabled flag

### ISSUE THREAD

**Issue by Vanuan** [jnicklas/capybara#1531]
Given this:

```
<select name="my-select">
  <option value="0" disabled="disabled">Disabled option</option>
  <option value="1">Enabled option</option>
</select>
```

When I do this:

```
select('Disabled option', :from => 'my-select')
```

Everything is fine, but I expect an exception to be thrown.

**Comment by twalpole** [comment]
We can't throw an exception currently (breaking behavior change) - but a warning does seem reasonable (like happens when attempting to set read only fields).  See PR #1532

**Comment by Vanuan** [comment]
At least it should not be selected. Thank you!
