### ISSUE TITLE
End of file reached (EOFError) when I used the function select

### ISSUE THREAD

**Issue by gelopfalcon** [jnicklas/capybara#1534]
Hello, please, I need urgent help. I have the following code 
![image1](https://cloud.githubusercontent.com/assets/4118271/8073507/2e0b7d16-0ee3-11e5-90b1-429dcfff5088.png)

I desire to select the option with value 1. I code the following code:

When(/^I click the radio button "([^"]*)"$/) do |locator|
  page.select locator, :from => 'edit-type'
end

The code is not bad, when capybara choose the option, i recieve in console the following error:
end of file reached (EOFError)

In the page web show me the following alert:
![mensagge](https://cloud.githubusercontent.com/assets/4118271/8073595/85d5b8c6-0ee4-11e5-88c4-556e2c42f20d.png)

The page use AJAX, exists some problem for use it?

Can you help me, please?

**Comment by twalpole** [comment]
As stated in the README, ask howtomquestions on the mailing list
