### ISSUE TITLE
Unable to locate and click on image element with id

### ISSUE THREAD

**Issue by ChinmayaTelstra** [jnicklas/capybara#1537]
Hi there,

I came across a blocker wherein i have to perform the click operation on an image (with an id), i tried xpath & css to locate this element and have failed to do it so far

Snippet of the source in the web page:
<img id="j_idt60:j_idt61:pdo" style="cursor:pointer;padding-right:4px;" onclick="document.getElementById('j_idt60:j_idt61:regionViewExportPDO').exportData();showMessageAfterDownload();" src="/vendor-customer-csll-gui-1.2-SNAPSHOT/javax.faces.resource/PDO.png.html?ln=images"/>

What was attempted and error thrown: (at option #3 - not sure how to avoid extra backspace "\" being added on the run?)

Option #1: page.find(:xpath, ".//*[@id='j_idt60:j_idt61:pdo']").click
-- Capybara::ElementNotFound: Unable to find xpath ".//*[@id='j_idt60:j_idt61:pdo']"

Option #2: page.find(:xpath, ".//*[@id='j_idt60\:j_idt61\:pdo']").click
-- Capybara::ElementNotFound: Unable to find xpath ".//*[@id='j_idt60:j_idt61:pdo']"

Option #3: find(:css, '#j_idt60\:j_idt61\:pdo').click
--Capybara::ElementNotFound: Unable to find css "#j_idt60\\:j_idt61\\:pdo"

Option #4: find(:css, '#j_idt60:j_idt61:pdo').click
--Selenium::WebDriver::Error::InvalidElementStateError: invalid element state: Failed to execute 'querySelectorAll' on 'Document': '#j_idt60:j_idt61:pdo' is not a valid selector.

Can any one here share their thoughts on how to overcome this issue?

Thanks in advance

**Comment by twalpole** [comment]
How to questions go in the mailing list as requested in the read every
