### ISSUE TITLE
visit

### ISSUE THREAD

**Issue by ostraaten** [jnicklas/capybara#1538]
I don't understand visit very well or at all. It seems so limited in functionality.

So for example I can use 

    visit 'devops.ok/crucible'

That makes sense and is useful.  We could also do something like

    visit 'http://devops.ok/crucible'

This also works. But I think it would also be useful to do something like

    visit '/crucible/admin'

I expected this to take me to http://www.devops.ok/crucible/admin but that is not the case. In fact this will take me to file:///crucible/admin.

Is it possible to navigate within a site using context path only?

The documentation does btw show examples like visit '/crucible/admin' but I think I confirmed that these do not work.

**Comment by twalpole** [comment]
Ask howto questions on the mailing list as requested in README
