### ISSUE TITLE
#raise_server_error! doesn't raise an exception when multiple sessions are created

### ISSUE THREAD

**Issue by yuki24** [jnicklas/capybara#1540]
Let's say multiple sessions are created while running the test suite and the app raises an exception in a certain situation. Each session makes a request to the same end point and the app will raise an exception. In this scenario, the first session can capture the exception, but the second one can't.

This is because [each session creates a server object](https://github.com/jnicklas/capybara/blob/5b6d65feaef0bbed661db607f9970a90730e1d2b/lib/capybara/session.rb#L66), but [only the first one creates a server thread](https://github.com/jnicklas/capybara/blob/5b6d65feaef0bbed661db607f9970a90730e1d2b/lib/capybara/server.rb#L66). And since the second session talks to the server thread created by the first session, the exception will be rescued by the first server object (more sepcifically, [a middleware object](https://github.com/jnicklas/capybara/blob/5b6d65feaef0bbed661db607f9970a90730e1d2b/lib/capybara/server.rb#L20-L21)).

The following test replicates the issue:

```ruby
# bug_report.rb
require 'capybara'
require 'selenium-webdriver'
require 'minitest/autorun'

class BugTest < Minitest::Test
  Capybara.current_driver = :selenium
  Capybara.app = ->(env) {
    raise "RuntimeError from the app"
  }

  def test_raise_server_error!
    session = Capybara.current_session
    session.visit("/")

    assert_raises RuntimeError, "RuntimeError from the app" do
      session.raise_server_error!
    end

    Capybara.using_session :another_session do
      session = Capybara.current_session
      session.visit("/")

      assert_raises RuntimeError, "RuntimeError from the app" do
        session.raise_server_error!
      end
    end
  end
end
```

And the result:

```
$ ruby bug_report.rb 
Run options: --seed 40314

# Running:

F

Finished in 0.752366s, 1.3291 runs/s, 2.6583 assertions/s.

  1) Failure:
BugTest#test_raise_server_error! [bug_report.rb:23]:
RuntimeError from the app.
RuntimeError expected but nothing was raised.

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by twalpole** [comment]
Yes - this is an issue -- not sure what the best solution is though, or whether the current behavior is good enough.  I don't think starting a new session to run a separate test on the same app is a normal use case.  Running a new copy of the app for each session is not a good solution either.

**Comment by twalpole** [comment]
Added some documentation about this issue - https://github.com/jnicklas/capybara/commit/404f9551042d78db76c583155910c4f98aa2447a  
Leaving this issue open for now

**Comment by Funfun** [comment]
Up vote.

**Comment by twalpole** [comment]
Can anyone provide a real world testing situation where it makes sense to create multiple sessions with the same app and test for a server error in one thats not the default session?

**Comment by twalpole** [comment]
Please try the per_session_server branch and see if that solves the issue you're having - I'm still not sold on this being an issue that is worth the downsides of this fix to solve, and wish I could implement it by just dynamically adding listeners to the existing server object and then storing the errors based on the port number of each session.  Unfortunately I think that would require stopping people from being able to set Capyara.server to guarantee Webrick use which can't really be done.

**Comment by twalpole** [comment]
This should be fixed in the master branch if you configure with Capybara.reuse_server = false
