### ISSUE TITLE
Understanding #all #first and synchronization.

### ISSUE THREAD

**Issue by metaskills** [jnicklas/capybara#1543]
This is a call for a behavior gut check. I am a long time user of Capybara and thought I was pretty versed in Capybara's [synchronization methods](http://www.elabs.se/blog/53-why-wait_until-was-removed-from-capybara). Recently it became obvious to me that #all and #first DLS methods both do not do an implicit wait or sync. Is this intended? It kind of feels right but I never fully understood this.

If it helps, I use Capybara mostly with Minitest and the DSL mixed into rails integration test cases. Here is a pry session where I was learning about this behavior:

```ruby
[21] pry(#MyIntegrationTest::whatever)> $ page.current_scope.all '.doesnotexist'
=> []
[21] pry(#MyIntegrationTest::whatever)> $ page.current_scope.first '.doesnotexist', wait: 2
=> []
[21] pry(#MyIntegrationTest::whatever)> $ page.current_scope.all

From: /Users/.../capybara-2.4.4/lib/capybara/node/finders.rb @line 144:
Owner Capybara::Node::Finders
Visibility: public
Number of lines: 8

def all(*args)
  query = Capybara::Query.new(*args)
  synchronize(query.wait) do
    result = query.resolve_for(self)
    raise Capybara::ExpectationNotMet, result.failure_message unless result.matches_count?
    result
  end
end
```

In each case the #all and #first did not wait. But reading the code, I felt it should. Could you throw down some knowledge? Also... thank you so much for all your work here. Huge fan.

**Comment by twalpole** [comment]
They don't wait by default because they are looking for 0 or more instances. If you want waiting to happen for them you need to use one of the numeric options (min, max, count, between). 

    page.all(:css, 'div.widget'). # will return immediately even if no widgets on page since 0 is an acceptable number of results

    page.all(:css, 'div.widget', min: 3) # will wait until at least 3 widgets on the page

In the future please ask these types of questions on the mailing list as requested in the README

**Comment by metaskills** [comment]
> They don't wait by default because they are looking for 0 or more instances.

That makes perfect sense. I love it. Thanks you so much for the enumerated recommendations as well. Cheers!
