### ISSUE TITLE
check/choose do not work with label values

### ISSUE THREAD

**Issue by killthekitten** [jnicklas/capybara#1548]
I can't choose/check options via default `check` /  `choose` helpers of capybara, while switching to `find` works:
```ruby
# Not working specs:
check("Alterna")
# => Unable to find checkbox "Alterna"
choose("Aveda")
# => Unable to find radio button "Aveda"

# Working specs:
find("label", text: "Alterna").click
find("label", text: "Aveda").click
```
HTML:
```html
<span class="checkbox b-survey__answer__choice">
  <input class="check_boxes optional g-checkbox" type="checkbox" value="3" name="survey_answer[choices_answer][]" id="survey_answer_choices_answer_3">
  <label class="collection_check_boxes" for="survey_answer_choices_answer_3">Alterna</label>
</span>
...
<span class="radio b-survey__answer__choice">
  <input class="radio_buttons optional g-checkbox" type="radio" value="2" name="survey_answer[choices_answer]" id="survey_answer_choices_answer_2">
  <label class="collection_radio_buttons" for="survey_answer_choices_answer_2">Aveda</label>
</span>
```

Setup is `capybara (2.5.0.dev)` + `poltergeist (1.6.0)`.

HTML snippets are from different steps of form and get rendered after an ajax call, just so you know*

**Comment by twalpole** [comment]
Are the checkbox and radio button visible?  If you are hiding them and highlighting the labels to show selected state, then this behavior is correct/as designed since a user cannot click on a hidden checkbox/radio button.

**Comment by killthekitten** [comment]
@twalpole yes, the elements are customized, so there is a big chance that they are hidden. I need to take a look later. 

Thank you for the idea. So is there a workaround? Click on the visible label still should change the value of a checkbox, why don't we support it?

**Comment by twalpole** [comment]
It is supported by doing exactly what you are doing -- find the label and click on  it.   #check and #choose are specifically defined to interact with the checkboxes and radio buttons.  If they're not visible on the page the user cant directly interact with them, so you cant use check or choose.

**Comment by killthekitten** [comment]
In fact, there are specs that are expecting this feature to work:
```
it "should choose a radio button by label" do
```
https://github.com/jnicklas/capybara/blob/3ae284460b1af35d40b077bf14f7222c2982c120/lib/capybara/spec/session/choose_spec.rb#L12

```
  it "should check a checkbox by label" do
```
https://github.com/jnicklas/capybara/blob/3ae284460b1af35d40b077bf14f7222c2982c120/lib/capybara/spec/session/check_spec.rb#L57

**Comment by killthekitten** [comment]
@twalpole labels are visible.

**Comment by twalpole** [comment]
Yes -- the labels are visible but the checkbox and radio button are obviously not -- check and choose can find by label text, but they interact directly with the checkbox and radio button -- if they are not visible on the page the user cannot directly interact with them

**Comment by killthekitten** [comment]
@twalpole but who cares does he can interact or not? I mean it's a default way of interaction with these elements, via labels.

**Comment by killthekitten** [comment]
@twalpole and the fact this behavior is not documented or mentioned in the exception message (stop me if I'm wrong), it makes debugging very complicated.

**Comment by twalpole** [comment]
Actually the default way of interacting with a checkbox is to click the checkbox - if there is a label attached to the checkbox then you can usually click the label too, however that is definitely the secondary method of interaction with a checkbox.  The bottom line is if you are hiding the checkbox or radio button, you can't use check or choose to interact with it -- do like you have done find the label and click it.

From the docs for #check  --  Find a check box and mark it as checked. The check box can be found via name, id or label text.  --  The "check box can be found", except it can't if its not visible on the page.  If you feel the docs need clarifying PRs are always considered.
