### ISSUE TITLE
#has_text? to accept an array of strings

### ISSUE THREAD

**Issue by andrii** [jnicklas/capybara#1551]
Please share your thoughts regarding `#has_text?` matcher being able to accept an array of strings that need to appear on the page only once.

Before
```ruby
expect(page).to have_text 'Apple Watch Sport'
expect(page).to have_text '38mm Silver Aluminum Case with White Sport Band'
expect(page).to have_text '$349.00'
```
After
```ruby
text = %q(
  Apple Watch Sport
  38mm Silver Aluminum Case with White Sport Band
  $349.00
).lines

expect(page).to have_text(text)
```
Would be happy to send the pull request.

**Comment by twalpole** [comment]
I'm not sold on this really gaining anything, since I tend to lean more towards having the tests be very clear about what is actually being checked for - If you actually have an array of text you can always just do

    array_of_strings.each { |s| expect(page).to have_text(s) }

, but for most cases its just clearer to write out each line.
