### ISSUE TITLE
invalid keys :visible when using have_content(..., visible: false)

### ISSUE THREAD

**Issue by vanboom** [jnicklas/capybara#1555]
This line
expect(page).not_to have_content(client.to_s, :visible=>false)

Produces this warning message...
invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait

Capybara 2.4.4

Can't we use visible=false to test for non-visible paragraph content? 

thanks!

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README

**Comment by obfuscoder** [comment]
Despite the question, the warning seems wrong to me. The visible option is listed as one of the possible accepted options. This should not produce the warning then.

**Comment by abotalov** [comment]
This is a duplicate of https://github.com/jnicklas/capybara/issues/1549
