### ISSUE TITLE
Make script_name configurable

### ISSUE THREAD

**Issue by betesh** [jnicklas/capybara#1557]
At line 5 of [lib/capybara/rails.rb](https://github.com/jnicklas/capybara/blob/3ae284460b1af35d40b077bf14f7222c2982c120/lib/capybara/rails.rb#L5), there is a hard-coded assumption that the app I am testing is rooted at "/"

    map "/" do

This is not a guarantee.  My Rails 4.2 application is configured with:

    ActionController::Base.relative_url_root = 
      Rails.application.routes.default_url_options[:script_name] =
      ActionMailer::Base.default_url_options[:script_name] =
      Rails.application.config.session_options[:path] = "some_nested_url"

so that the application lives at https://mydomain.com/some_nested_url.

To tell Capybara this, I have to monkey-patch the entire `Capybara.app = Rack::Builder.new do ...` in the above file.

Instead of "/", the argument to `map` should really be:

    ActionController::Base.relative_url_root.presence || '/'

This could even be a configurable option, with `ActionController::Base.relative_url_root.presence || '/'` as the default.

If I a PR that addresses this, will it be accepted?  Should I make it configurable or just check for `relative_url_root`?

**Comment by twalpole** [comment]
Is setting ActionController::Base.relative_url_root alone enough to make a an app work in a subdirectory?  From my quick (very quick and very minimal) test it isn't and seemed only to change the url of asset links.  If it alone isn't sufficient then using it for the mount point is going to create more issues.   lib/capybara/rails.rb should really be taken as the basic case and an example for more complex cases.  If you have a more complex case copy the contents of the file into your own rails_helper.rb (or whatever file you configure your test setup from) and modify it as needed

**Comment by betesh** [comment]
>  If you have a more complex case copy the contents of the file into your own rails_helper.rb (or whatever file you configure your test setup from) and modify it as needed

That's what I'm doing, but I wouldn't call my case "more complex".  In production, it's mounted at a relative_root_url -- nothing particularly complex there.  I want Capybara to match production as much as possible, and since I have a `mount "some_nested_url" do` block in `config.ru`, I want one in Capybara.app as well.  It seems to be that the default should be for the two environments to match.

**Comment by twalpole** [comment]
Ok - then all you need to do is override the default app created

    require 'capybara/rails'

    Capybara.app = Rack::Builder.new do
      map "some_nested_url" do
         run Rails.application
      end
    end.to_app

Basing the mount point on the setting of ActionController::Base.relative_url_root isn't correct since setting that alone doesn't appear to bet enough to get a rails app to work in a subdirectory, and it's not really worth figuring out all the settings and logic across multiple versions of rails that would be required to be checked instead of 5 lines in a users helper file.
