### ISSUE TITLE
fill_in a long text results in timeout

### ISSUE THREAD

**Issue by shoshRose** [jnicklas/capybara#1560]
Using Cpaybara + Rspec + Selenum .
Trying to fill in a textarea with a **very** long string:
```
fill_in 'agreeText', :with => contents
```
results in:
```
Failure/Error: fill_in 'agreeText', :with => contents
          Net::ReadTimeout:
            Net::ReadTimeout

```
any idea how to resolve?

**Comment by twalpole** [comment]
How long is "very long"? What driver are you using? Also, if you can provide a minimal test case that would be great.

**Comment by twalpole** [comment]
Closing due to lack of response
