### ISSUE TITLE
Capybara::Result does not define :to_ary method

### ISSUE THREAD

**Issue by githorse** [jnicklas/capybara#1562]
I often write matchers that take an argument that might be either a single object or a collection, e.g.

    expect(things).to be_foobared
    expect(thing).to be_foobared

I could then write the matcher like this, in theory:

    RSpec::Matchers.define :be_foobared do
      match do |actual|
        Array.wrap( actual ).each do |element|
          return false unless element.has_css? '.foobar' 
        return true
      end
    end

The `Array.wrap` method does exactly what I want here -- wraps a single object in an array or calls `.to_ary` on an Enumerable object (i.e., leaves it unchanged for my purposes). Problem is, though `Capybara::Result` defines the `.to_a` method as expected, it does not define the corresponding implicit `.to_ary` method, so `Array.wrap` doesn't work here. Any reason that shouldn't be patched?

**Comment by twalpole** [comment]
Capybara::Result is not an array, and doesn't implement all the methods Array supports.  My understanding is that #to_ary should only be implemented for objects that are derived from Array or implement all the methods Array supports - see https://bugs.ruby-lang.org/issues/3685

**Comment by twalpole** [comment]
FYI: you should should just be able to do  Array(actual)  since that will move on to trying #to_a if #to_ary is not provided

**Comment by githorse** [comment]
thanks @twalpole -- I didn't realize Array() would do that. That works.
