### ISSUE TITLE
Adfs authentication with capybara

### ISSUE THREAD

**Issue by KaterynaTs** [jnicklas/capybara#1572]
Hello Team,
Could you please help me, I haven't found anything about this question in the internet - how to perform adfs authentication with capybara?
On the beginning of page loading I have this login pop-up:
<img width="476" alt="screen shot 2015-09-08 at 14 42 53" src="https://cloud.githubusercontent.com/assets/3985704/9733997/6bab7c92-5638-11e5-8b15-4dbaebb78048.png">
are there ways to enter login and password?

Thank you!

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README

**Comment by KaterynaTs** [comment]
Thank you, [done in Google group](https://groups.google.com/forum/#!topic/ruby-capybara/X1RQGUjMVDM).
