### ISSUE TITLE
'IOError: stream closed' with Poltergeist after calling session.driver.quit

### ISSUE THREAD

**Issue by wakproductions** [jnicklas/capybara#1577]
I am using Capybara 2.4 for web page scraping and was having a memory leak issue with phantomjs remaining in memory and consuming resources. According to the Poltergeist webpage, they suggest using a Capybara method to fix this problem:

    session.driver.quit

Now the issue is that whenever I do Capybara.visit after quitting the driver, I receive the error:

    IOError: closed stream

I believe resetting the session should fix this, but I get the same error whenever I call any of the _reset! methods on the session or driver. Is there a way to just initialize a new session object?

**Comment by twalpole** [comment]
Capybara doesn't support operation after you call driver specific messages on the poltergeist driver, you should post this question either in the mailing list or over on the poltergeist project
