### ISSUE TITLE
Clearing tmp files

### ISSUE THREAD

**Issue by amnesia7** [jnicklas/capybara#1583]
html files produced by capybara when running `save_and_open_page` are saved in `tmp/capybara` which from time to time needs clearing out.

I noticed this page on SO http://stackoverflow.com/questions/19342578/how-to-make-rake-tmpclear-also-clear-tmp-capybara and wondered if capybara should be applying this task to rake somehow for clearing capybara tmp files as part of `rake tmp:clear` or have I missed something and should it be already doing it?

**Comment by twalpole** [comment]
Capybara doesn't do any cleanup of tmp files -- you need to handle that yourself

**Comment by amnesia7** [comment]
Just got a response from rails issue about this and looks to be a straightforward addition to allow this cleanup to be added if it's worth it: https://github.com/rails/rails/issues/22050#issuecomment-150812209

Any more thoughts @twalpole or is it still not worth adding?

**Comment by twalpole** [comment]
where to save the files by default is set by Capybara.save_and_open_page_path - so if a user sets that in code that isn't loaded by the Rakefile then the task would be cleaning the wrong thing, also Capybara isn't rails only so adding this for everyone wouldn't make much sense.  
Capybara won't be adding this to the project, if you want it in your projects as explained in the rails teams response it's easy enough to add.
