### ISSUE TITLE
Chaining #text to #all reveals hidden elements

### ISSUE THREAD

**Issue by Nakilon** [jnicklas/capybara#1584]
Looks like chaining `#text` doesn't mind nodes visibility:
```
irb> all(".data-io label").map(&:text)
=> ["Campaign", "User"]
irb> all(".data-io label").text
=> "Dashboard All accounts Account ... Campaign ... User ..."
```
Shouldn't it be described somewhere in docs or is it a bug?

**Comment by twalpole** [comment]
all returns a Capybara::Result object which doesn't have a #text method, so I'm not really sure what code you're calling.  Have you added methods to Capybara::Result?  If you've included the capybara dsl into Object, then I guess it could be calling capybaras text method, but that would be calling it for the entire page and the result could be what you've pasted.  Either way this isn't a bug in Capybara.
