### ISSUE TITLE
Impossible to match value of an input that has been updated by js with no label, id, or name 

### ISSUE THREAD

**Issue by phillc** [jnicklas/capybara#1587]
Hello,

I have an input field with no name, id or label, that I need to write an expectation on.

You can target this with a css selector using the `input[value='foo']` or a similar xpath, because it will match all inputs regardless.

However, in my case, the value of the input is being changed by javascript. An xpath selector would fail in this case because ["The XPath query is run against the html document so doesnt access the value property."](https://github.com/jnicklas/capybara/issues/1061). The css selector form fails because it does not wait for the value to change. The normal way to solve this would be to use `expect(page).to have_field(..)`. However, the [field selector passes down the first argument to XPath::HTML.field](https://github.com/jnicklas/capybara/blob/6659722b7d16eb48676a5e0a595ee5da913f5f5b/lib/capybara/selector.rb#L129). XPath::HTML.field takes that argument and [tries to match that argument to id, name, label or placeholder](https://github.com/jnicklas/xpath/blob/master/lib/xpath/html.rb#L170). 

However, in my case, I have none of those. I just want to be able to match an input, regardless of attributes.

To give context, I am using react, and react is what is controlling, changing, and recording the value of the input field behind the scenes, so I do not need to assign it a name or id.

One solution could be to put a condition at the [point in which we call out to XPath](https://github.com/jnicklas/capybara/blob/6659722b7d16eb48676a5e0a595ee5da913f5f5b/lib/capybara/selector.rb#L129), and if the locator is `nil` or perhaps some symbol like `:any`, just do a normal xpath search for any input, textarea or select.

Thanks

**Comment by twalpole** [comment]
I haven't specifically tried it but I would guess

    expect(page).to have_field('', with: 'expected value')

would probably do what you want, if not you can always add your own selector type with Capybara.add_selector and then do

  expect(page).to have_selector(:custom_selector, 'selector', filter1: 'blah blah', ...)  

with whatever type of xpath and filters you want

**Comment by phillc** [comment]
Empty string and nil do not work in this case.

Will try adding my own selector, thanks.
