### ISSUE TITLE
Ajax on page load to externat servers

### ISSUE THREAD

**Issue by lmuntaner** [jnicklas/capybara#1589]
I have a page that on page load, does an ajax request to an external server. I want to mock that request.

I have been using sinon.js to mock the ajax requests to external servers when there is a DOM event. In this case is easy since I create a sinon server right before testing the event. After triggering the event with Capybara I respond to the request with sinon and it works.

However, when the request is made on page load. I can't create the server and respond before the ```visit url```, because the request is not yet made. However, when I create and respond after the ```visit url``` it is too late since my request has already failed.

Could there be a way to pass a block to the #visit method maybe?

Thanks!

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README

**Comment by lmuntaner** [comment]
Oops!! So sorry about that!!
