### ISSUE TITLE
why cannot call #assert_current_path ?

### ISSUE THREAD

**Issue by JevanWu** [jnicklas/capybara#1590]
I want to compare the expected path and current path to justify whether the test is passed

I found the method Capybara::SessionMatchers#assert_current_path. I guess this method can fulfill my requirement. 

But when i wrote 

```ruby

page.assert_current_path()

```

in my test, the error showed no #assert_current_path method

I've seen the Capybara::Session has included the Capybara::SessionMatchers. I'm confused of why i cannot call the #assert_current_path method. Does Capybara have the functionality to compare current path and expect path? coz use page content to justify the result is not stable for me. 

Thanks in advance!

**Comment by twalpole** [comment]
Ask "how to" questions on the mailing list as requested in the README
