### ISSUE TITLE
Which driver supports fill_in with fill_options?

### ISSUE THREAD

**Issue by m1racoli** [jnicklas/capybara#1591]
The command
```ruby
fill_in(locator, with: 'text to fill in', fill_options: {blur: false})
```
triggers the error message
```Options passed to Capybara::Node#set but the driver doesn't support them```
on Mac OSX 10.11 using either poltergeist or capybara-webkit driver.
Which driver supports the `fill_options` functionality?

**Comment by twalpole** [comment]
Ask "how to" questions in the mailing list as requested in the README
