### ISSUE TITLE
open_new_window returning "opened 0 windows instead of 1"

### ISSUE THREAD

**Issue by aadoello** [jnicklas/capybara#1593]
Hi guys, I had some code working until it started failing some days ago (possibly since Chrome got updated). I'm using the `open_new_window` function. I've isolated it and it still fails...

Ruby version: 2.1.2
Selenium driver + Chrome v46.0.2490.71 (64-bit)

Code:
```
it "dummy" do
  within_window open_new_window do
    visit 'http://www.google.es'
  end
end
```

Error:
```
  1) dummy
     Failure/Error: within open_new_window do
     Capybara::WindowError:
       block passed to #window_opened_by opened 0 windows instead of 1
     # ./spec/dummy.rb:40:in `block (2 levels) in <top (required)>'

Finished in 4.14 seconds (files took 3.43 seconds to load)
1 example, 1 failure
```

Any clue?

Thanks in advance!

**Comment by twalpole** [comment]
One possibility is that Chrome is taking longer to open the new window, could you try increasing `Capybara.default_max_wait_time` and see if that fixes things for you?  If so we probably need to allow passing the :wait option through `#open_new_window`

**Comment by aadoello** [comment]
Hi Thomas,

Thanks for your help. Unfortunately I already tried that. I set it to 10
seconds and didn't work. I don't think it's time-related, it's more like
Capybara just can't open the window and doesn't realise about it... any
other idea?

2015-10-29 17:01 GMT+01:00 Thomas Walpole <notifications@github.com>:

> One possibility is that Chrome is taking longer to open the new window,
> could you try increasing Capybara.default_max_wait_time and see if that
> fixes things for you? If so we probably need to allow passing the :wait
> option through #open_new_window
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnicklas/capybara/issues/1593#issuecomment-152226108>.
>



-- 
Best Regards,

Alvaro Almagro Doello
Automated Test Engineer at FinancialForce.com
Twitter <https://twitter.com/Alvaro_Almagro> - LinkedIn
<https://www.linkedin.com/in/alvaroalmagro>

**Comment by twalpole** [comment]
Well Capybara does realize it can't open the window - that's what the error is saying :)   All calling open_new_window does is execute "window.open()" in the browser, so as long as there is a current browser on which to call that then there aren't really many things to go wrong.  A few things to try

1.  visit a page before calling open_new_window to make sure there is actually a browser window to run the JS in

2. update to the latest chrome_driver

3. Make sure your chrome isn't configured to block new windows

This is behavior that is tested for in capybaras specs and is currently passing on travis with latest chrome_driver and latest chrome

**Comment by twalpole** [comment]
Closing due to lack of followup
