### ISSUE TITLE
capybara with selenium giving incorrect actioncontroller response

### ISSUE THREAD

**Issue by bytenel** [jnicklas/capybara#1594]
I have some code in a controller laid out like the following that does a redirect to an external url. This code works in my actual environment but when the test I wrote below runs using capybara with selenium I get a routing error. I shouldn't get a routing error since I should just be doing a redirect to an external service. Not sure whats up here, I think it's a bug in capybara.

spec
```
 before :each do
    @business = create(:business, :setup)
    @user     = create(:owner_user, business: @business)
    @admin    = create(:admin_user, business: @business)
  end

  it 'redirects show requests to squarespace with the right url' do
    create(:post,
           title: '5 ways to stay healthy when chained to a desk all day',
           tag: 'healthy'
    )
    login(@user)
    visit blog_path(id: '5-ways-to-stay-healthy-when-chained-to-a-desk-all-day')
    expect(current_path).to be_redirect_to 'https://blog.site.co/healthy/5-ways-to-stay-healthy-when-chained-to-a-desk-all-day'
  end
```

controller
```
 def squarespace_url
    'http://blog.site.co'
  end

  def redirect_to_squarespace
    post_to_view = request.path.split(/blog/)[1] || ''
    redirect_to "#{ squarespace_url }#{ post_to_view }" and return
  end

  def show
    redirect_to_squarespace
  end
```

**Comment by twalpole** [comment]
What exactly is the error?  what is be_redirect_to? and are you 100% sure that you're running it with the selenium driver and not with the rack-test driver?

**Comment by twalpole** [comment]
Capybara is for use in integration/feature tests.  Since browsers actually follow redirects you can't check for them other than checking you end up on the final url - if you want to verify that a redirect (http 301, 302) is returned you should be doing that in a controller/request spec.  Also comparing to current_path immediately when using real browsers is problematic because visit can/will return before the browser has actually completed its requests.  If you want to check that a browser ends up on a specific page you should be using

    expect(page).to have_current_path('https://blog.site.co/healthy/5-ways-to-stay-healthy-when-chained-to-a-desk-all-day', url: true)  

which will utilize Capybaras waiting behavior for the page url to change

**Comment by bytenel** [comment]
Sorry on the late response - yes I am sure I'm running it with the selenium driver. The problem was that I was getting a 
```
ActionController::RoutingError: No route matches GET xyz
```
where xyz was the route that I was redirecting to (outside of my site) based on the posting in my controller, it was a strange problem. I agree that it could be easier to just check that a redirect is returned from a controller spec but it seems odd that the behavior in Capybara would lead to a no route error when clearly the item does a redirect outside of the application. I appreciate you pointing out the have_current_path matcher!

**Comment by twalpole** [comment]
It shouldn't lead to a no route error unless you haven't tagged the test for js and are therefore using the rack-test driver which ignores the hostname

**Comment by bytenel** [comment]
Hm, it appears that my spec helper didn't infer my spec type correctly based on location and was defaulting to rack-test. My apologies on that! I still get the following error though after using the code you posted:
```
 Failure/Error: expect(page).to have_current_path('https://blog.site.co/healthy/5-ways-to-stay-healthy-when-chained-to-a-desk-all-day', url: true)
       expected #<Capybara::Session:0x007fef1b6eb218> to respond to `has_current_path?`
```

**Comment by twalpole** [comment]
Make sure you're using capybara 2.5

**Comment by bytenel** [comment]
Updated, appears to be working now. Thanks @twalpole ! I'll be sure to give you a twitter shout out :)
