### ISSUE TITLE
Capybara does not parse the element?

### ISSUE THREAD

**Issue by nambrot** [jnicklas/capybara#1602]
```
element['innerHTML']
=> "<div class=\"patient-row-badge\" data-badge=\"1\" data-reactid=\".0.$PatientsIndexComponent.1.0.0.3.0.$All Patients.3.$code1.0.3.1.0\"></div>"
element.all('*')
=> []
````

I couldn't reproduce it but does anyone know why this would happen?

**Comment by twalpole** [comment]
Ask questions on the mailing list as requested in the README

**Comment by nambrot** [comment]
Sorry. Fwiw, I figured it out why it failed. Adding an empty space inside the `div` makes it discoverable for Capybara

**Comment by twalpole** [comment]
Correct because without content or set sizes a div is not visible on the page -- asking on the mailing list would have got you the answer
