### ISSUE TITLE
have_text always pass on a 500 error

### ISSUE THREAD

**Issue by Bastes** [jnicklas/capybara#1604]
(sorry, I initially accidentally hit the return button before filling in the description ^^° here goes)

I'm using capybara 2.5.0 along with rspec-rails 3.4.0.

In a feature spec scenario I haven't yet implemented, my spec passes with something akin to:
```ruby
expect(page).to have_text "Something that is obiously not yet there"
# and also
expect(page).to have_content "Something that is obiously not yet there"
```

I don't know how this could pass. I've been following the rspec documentation: https://www.relishapp.com/rspec/rspec-mocks/v/3-3/docs/setting-constraints/matching-arguments

Each time I tried to fill in a field that wasn't there, click on a link or button that wasn't there, it failed as expected. Only when I use have_text or have_content does it always pass, regardless of what the code does.

Hope it helps ^^ I don't know where to start debugging the code myself ^^°

**Comment by Bastes** [comment]
A little digging later with pry-byebug reveals that:
```ruby
page.assert_text "Anything that shouldn't be there"
```
Always yields "true" somehow in my context. I tried then:
```ruby
page.html
```
What I got was (as expected) the error message from the controller (the controller create action hasn't been implemented yet, so it ends in a 500 error). Of course, the content the matcher shouldn't be finding yet finds is nowhere in this content.

I'll continue digging to see what I can find.

**Comment by Bastes** [comment]
More digging:
If I try to assert wether text is there on a page that's implemented (not a 500 error) the check is made and fails when it should, succeeds when it should.

**Comment by twalpole** [comment]
This is something that is pretty heavily tested in this project so I would doubt there's an error with it Capybara (not impossible, just highly unlikely).  Much more likely is that your 500 error page is showing the source code of where the error was thrown from on it, which will include the text you're searching for.

**Comment by Bastes** [comment]
That could explain it ; I'll see wether the string was part of the error.

Though, and I don't mean to criticize just for the sake of it, I'd be less surprising if Capybara was to fail the scenario automatically when it receives a 500 error (with of course some way to disable that behaviour on the off-chance someone actually needs to check that a 500 error is raised through a scenario?). As a project maintainer, I'd be interested in tests failing when the app crashes through a scenario ^^

**Comment by Bastes** [comment]
@twalpole Diagnosis confirmed ^^d I'll patch my own spec to check wether a 500 error happened, but in case you have an idea on how to implement a safeguard to raise an error automatically in a scenario when a 500 error is raised, I'd be glad to contribute and try to implement it.

**Comment by twalpole** [comment]
@Bastes If the app actually raised an error then Capybara will raise the error and fail the test (assuming Capybara.raise_server_errors is true (default) ), however in your case the app isn't actually raising an error, its returning a valid webpage - just happens to be a webpage about an internal error the app caught.

**Comment by twalpole** [comment]
@Bastes Also you could probably turn off whatever is producing detailed error pages in test mode - you wouldn't want that info displayed in production mode, so by default have it off in test mode too.  (If in rails check that better-errors isn't loaded in the test environment for instance - not sure what other settings might need to be checked).  Then the source code won't be displayed in the error page, and your test will correctly fail/pass

**Comment by Bastes** [comment]
@twalpole Ah, there's the culprit then. Thanks a lot for your help, better_errors was indeed loaded in dev and test mode, and disabling it raises the errors in the scenario as it should.

Cheers, and sorry for the noise ^^°

**Comment by tarr11** [comment]
This happened to me as well.  It was very confusing behavior.
