### ISSUE TITLE
Capybara does not respected deleted session variable

### ISSUE THREAD

**Issue by githorse** [jnicklas/capybara#1605]
I can't sign out of my app in RSpec/Capybara. A failing example:

````
# SessionsController (logic basically that of Hartl RoR tutorial)
def destroy
  sign_out if signed_in? 
  puts "in SessionsController#destroy: session[:user_id] == #{session[:user_id] || 'nil'}"
  redirect_to root_path
end

def sign_out
  forget current_user
  session.delete(:user_id)
  @current_user = nil
end
````

I run a simple log-in, log-out example:
````
def test  # test_path
  puts "in SessionsController#test:    session[:user_id] == #{session[:user_id] || 'nil'}"
end

scenario 'sign out should work' do
  sign_in @user
  visit test_path
  sign_out
  visit test_path
end

$ rspec spec.rb
Output:
in SessionsController#test:    session[:user_id] == 1
in SessionsController#destroy: session[:user_id] == nil
in SessionsController#test:    session[:user_id] == 1
````

The `user_id` is somehow being persisted in the session after its deletion in the `sign_out` method. If I follow the same steps in the browser manually, I get

````
in SessionsController#test:    session[:user_id] == 1
in SessionsController#destroy: session[:user_id] == nil
in SessionsController#test:    session[:user_id] == nil
````

as expected. Since this problem is occurring within a single test, I don't think this is a `Capybara.reset_sessions!` issue. What am I missing here?

**Comment by twalpole** [comment]
Please ask howto questions in the mailing list as requested in the README, and include details about which driver you're using, what the steps are doing, etc.  As a guess though I would say you're using selenium as the driver and your sign_out step isn't looking for any results after redirecting to the root path , so the second visit test_path is actually occurring before the sign_out redirect occurs, so cookies in the browser aren't actually getting reset

**Comment by githorse** [comment]
Hi @twalpole, I'm using the Poltergeist driver actually. I'm still confused about how to get this working, since the redirect does not get performed even if I add a line after `sign_out`:

````
expect(page).to have_content 'something on root path'
````

I've posted this on the mailing list [here](https://groups.google.com/forum/#!topic/ruby-capybara/y_Eay2zTvfc).
