### ISSUE TITLE
Microsoft Edge cannot find xpath "/html/body/*"

### ISSUE THREAD

**Issue by haonoy** [jnicklas/capybara#1606]
I'm getting errors after every scenario, the problem is this:

<pre>
Locator not implemented (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 41 milliseconds
      Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
      System info: host: 'IE11WIN10', ip: '192.168.179.55', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_66'
      Driver info: org.openqa.selenium.edge.EdgeDriver
      Capabilities [{acceptSslCerts=true, browserVersion=20.10240.16384.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
      Session ID: 014D2248-D569-4DAE-8767-63DA160464B2
      *** Element info: {Using=xpath, value=/html/body/*} (org.openqa.selenium.WebDriverException) (Selenium::WebDriver::Error::UnknownError)
      [remote server] sun.reflect.GeneratedConstructorAccessor11():-1:in `newInstance'
      [remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'
      [remote server] java.lang.reflect.Constructor():-1:in `newInstance'
      [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):206:in `createThrowable'
      [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):158:in `throwIfResponseFailed'
      [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):647:in `execute'
      [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):378:in `findElements'
      [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):494:in `findElementsByXPath'
      [remote server] org.openqa.selenium.By$ByXPath(By.java):356:in `findElements'
      [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):341:in `findElements'
      [remote server] sun.reflect.GeneratedMethodAccessor14():-1:in `invoke'
      [remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
      [remote server] java.lang.reflect.Method():-1:in `invoke'
      [remote server] org.openqa.selenium.support.events.EventFiringWebDriver$2(EventFiringWebDriver.java):102:in `invoke'
      [remote server] com.sun.proxy.$Proxy1():-1:in `findElements'
      [remote server] org.openqa.selenium.support.events.EventFiringWebDriver(EventFiringWebDriver.java):176:in `findElements'
      [remote server] org.openqa.selenium.remote.server.handler.FindElements(FindElements.java):50:in `call'
      [remote server] org.openqa.selenium.remote.server.handler.FindElements(FindElements.java):1:in `call'
      [remote server] java.util.concurrent.FutureTask():-1:in `run'
      [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
      [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
      [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
      [remote server] java.lang.Thread():-1:in `run'
</pre>

Browser : Microsoft Edge
OS : Windows10
Tested with cucumber/capybara

**Comment by twalpole** [comment]
According to http://stackoverflow.com/questions/31748000/not-able-to-locate-the-element-using-xpath-locator-for-edge-driver-instance-of-s there is no xpath support in Edge, which would mak capybara unusable with it - I don't currently have access to a  Windows 10 system to test with so can't confirm it myself

**Comment by twalpole** [comment]
Here's a status page for for the edge webdriver - https://dev.windows.com/en-us/microsoft-edge/platform/status/webdriver/details/ - not sure if I'm reading it correctly but I think it's saying there's a preview release of the driver that has xpath support

**Comment by haonoy** [comment]
@twalpole Thank you for your answer - you can download Windows10 virtual machine from https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/ :)
