### ISSUE TITLE
Capybara cannot work in a loop?

### ISSUE THREAD

**Issue by KingsleyZ** [jnicklas/capybara#1608]
I am writing a massive to test UI. Basically after you click a button (id=add-split-transaction), a new row will be append to the UI with div id split-transaction-3. Click the button again, a new div block split-transaction-4 will be generated.

Here is the code. I am trying to generate 100 rows but it says cannot find split-transaction-3. If I don't put everything in a loop. It works. 

    # count = 3
    # while count < 103
    #   find('#add-split-transaction').click
    #   expect(page).to have_css "split-transaction-#{count}"
    #   count += 1
    # end

So my question is why does capybara not working in a loop? Thanks.

**Comment by twalpole** [comment]
Ask howto questions in the mailing list as requested in the README
