### ISSUE TITLE
1.9.3 support is broken due to mime-types dependency

### ISSUE THREAD

**Issue by xaviershay** [jnicklas/capybara#1615]
mime-types 3.0 removed support for Ruby 1.9.3.

> Version 3.0 is a major release that requires Ruby 2.0 compatibility and removes deprecated functions.

ref: https://github.com/mime-types/ruby-mime-types/

Capybara depends on `>= 1.16`, and claims 1.9 support in the README.

This was previously reported for mime-types 2.0 at https://github.com/jnicklas/capybara/issues/1173, where it was suggested to switch to a `~>` dependency instead. Given this is the second time it has broken, thoughts on doing so this time?

I discovered this because `simplecov`'s 1.9 build was failing due to a transitive dependency on mime-types through capybara.

**Comment by twalpole** [comment]
I see no reason to limit people running ruby 2.0+ to mime-types < 3 - yes if you're still running 1.9.3 you will need to lock mime-types in your own gem file, but capybara works with 2 or 3

**Comment by xaviershay** [comment]
at the very least shouldn't this be called out in the README? It currently claims 1.9 support with no caveats, but it won't work out of the box.

(FWIW I'd be ok with just officially dropping 1.9 support since it was EOLed in February)

**Comment by twalpole** [comment]
The fact is that Capybara will work with any available version of mime-types >= 1.16  -- mime-types v3+ won't work with ruby 1.9.3 but that's not a limitation of capybara, its really a limitation of bundler and the gem dependency system that it won't pick a lower acceptable version of mime-types when running with ruby < 2.  The error message that is returned is pretty clear - "Gem::InstallError: mime-types-data requires Ruby version >= 2.0" and if a user adds mime-types < 2.0 to their Gemfile capybara will work just fine.   If you wan't to submit a PR for documentation that will be considered but this really isn't a Capybara issue  ( ie. Capybara works with any version of mime-types >= 1.16 that the ruby you are using will support)

**Comment by deivid-rodriguez** [comment]
The build should be fixed though (or the failures ignored / 1.9 support dropped).

It could be possible too to specified correct conditional dependencies with a hack like this: https://github.com/astashov/debugger-xml/commit/c67ef5b88e168cfebab30231017710f39e3b36c9.

**Comment by stby-telstra** [comment]
I'm a newbie trying to build and install the capybara-webkit gem, following the Windows instructions in [https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit].

I'm tripping up on the last step in the instructions with the mime-types error ("mime-types-data requires Ruby version >= 2.0."), because I've followed the instructions pretty closely and used Ruby 1.9.3.

I'd just like to know, where and how do I "lock mime-types in your own gem file", as twalpole has suggested?

Thanks in advance.

**Comment by gtbono** [comment]
I'm having the same issue on a Debian Wheezy and Ubuntu 14.04 installation, both with Ruby 1.9.3 installing Rails 4.2.6, did any of you guys got it working?

**Comment by twalpole** [comment]
@gtbono If your problem is your project not installing then in your projects Gemfile specify `gem 'mime-types', '< 3.0'` , if your problem is building capybara-webkit then thats a different project and you would need to ask over on it.
