### ISSUE TITLE
Capybara not found element with japan text 

### ISSUE THREAD

**Issue by vihc** [jnicklas/capybara#1618]
The page have header ``` <meta http-equiv="Content-Type" content="text/html; charset=shift_jis">```,  select tags
```html 
   <select name="sel01" id="sel01" size="18" style="width:300px" >
	 <option value="1">1:株式会社テスト</option>
	 <option value="2">2:株式会社ブレインテスト</option>
	 <option value="3">3:株式会社VIテスト</option>
	 <option value="4">4:株式会社AER</option>
    </select>
```
I want click  ``` <option value="2">2:株式会社ブレインテスト</option> ```
but  is not working with code  ``` select('2:株式会社ブレインテスト',  from: 'sel01')``` 
It is happen  errors  ``` Capybara::ElementNotFound: Unable to find option "2:株式会社ブレインテスト" ```

I using debug to see text  of  option tag '2:株式会社ブレインテスト'. 
This is capybara wrong encoding.  
``` find(:xpath, "//*[@id='sel01']/option[@value='2']").text```  =>  "2:譬ｪ蠑丈ｼ夂､ｾ繝悶Ξ繧､繝ｳ繝�せ繝�"

Help me ! 

I want  using  method #select(value, options = {})

**Comment by twalpole** [comment]
Using

    <!DOCTYPE html>
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=shift_jis">
        <title>japanese</title>
      </head>

      <body id="with_js">
        <select name="sel01" id="sel01" size="18" style="width:300px" >
          <option value="1">1:株式会社テスト</option>
          <option value="2">2:株式会社ブレインテスト</option>
          <option value="3">3:株式会社VIテスト</option>
         <option value="4">4:株式会社AER</option>
        </select>
      </body>
    </html>

the test

    @session.visit('/japanese')   
    @session.select('2:株式会社ブレインテスト', from: 'sel01')
    expect(@session.find_field('sel01').value).to eq('2')

works fine for me with both the rack_test and selenium drivers - If you're using a different driver it may be a bug in that driver and should be reported on that drivers project, otherwise you'll need to provide a minimal failing example
