### ISSUE TITLE
passing disabled: :all to find_field returns an error

### ISSUE THREAD

**Issue by cguanzon** [jnicklas/capybara#1626]
I'm using Capybara 2.5

Issue: 
this line: `find_field('stateAuthority', disabled: :all)` returns an error in my tests

```
NoMethodError:
       undefined method `^' for :all:Symbol
``` 

documentation: http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FFinders%3Afind_field

thanks for your time.

**Comment by twalpole** [comment]
You're reading the docs for the master branch, if you look at the docs for the version you're using - http://www.rubydoc.info/gems/capybara/2.5.0/Capybara/Node/Finders#find_field-instance_method you'll see that feature isn't supported.  If you want to use it you'll need to specify the master branch of Capybara in your Gemfile for now

    gem 'capybara', github: 'jnicklas/capybara'
