### ISSUE TITLE
rails5 / devise / wrong number of arguments for visit

### ISSUE THREAD

**Issue by bbnnt** [jnicklas/capybara#1629]
hi,
just to know first if it was actually ready to use it with rails5

Then, compared to the use i could have in previous rails version, I'm quite stuck with (for example) the following :

`Failure/Error: visit("/users/sign_in")
     ArgumentError:
       wrong number of arguments (0 for 1..2)`

And it goes like this for any urls listed in routes that have been tried, that involves devise (a direct access to the singeing page, a redirect to a signin page, etc)
thanks for clarifying or some help on this one

**Comment by twalpole** [comment]
I assume you're using the rack_test driver, if so use the master branch with rack 2.0

**Comment by bbnnt** [comment]
@twalpole I have those two in my gemfile :/
```
gem 'rack', '~> 2.x'
...
group :development, :test do
    gem "capybara", :github => 'jnicklas/capybara', :branch => 'master'
end
```

**Comment by twalpole** [comment]
Hmmm, then can you provide a reproducible test case or at the very least a stack trace so we can see where the error is coming from - see CONTRIBUTING.md
