### ISSUE TITLE
capybara instalation and procedure

### ISSUE THREAD

**Issue by karunakarkarna** [jnicklas/capybara#1633]
I want to write some acceptance test cases for a website using capybara with selenium webdriver, but i dont know how to start and write test cases ,can you please any one tell me the sample example for that, I tried in many ways with the help of google but i have not received the exact details of it, Please provide me a doc if possible. that is very impotent for me. 
example:
I want to open just like google URL (https://www.google.co.in/)  ,and search somthing and click on submit . please help me.
thanks in advance......

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README
