### ISSUE TITLE
Release Capybara 2.6

### ISSUE THREAD

**Issue by twalpole** [jnicklas/capybara#1634]
@jferris @mhoran @jonleighton @route   -  Just a heads up that I plan to hopefully release Capybara 2.6 this coming weekend.  I don't believe there is anything that should affect driver authors, it's mainly to get released support for rack 2.0 (rails 5) in the rack_test driver.

**Comment by mhoran** [comment]
Thanks for the heads up! We'll follow close behind with a release of capybara-webkit. Could you ping us on this thread when it's out?

**Comment by twalpole** [comment]
Will do

**Comment by route** [comment]
Thanks for updates!

**Comment by twalpole** [comment]
@jferris @mhoran @jonleighton @route - 2.6.0 is released
