### ISSUE TITLE
Sidekiq, Capybara, Poltergeist, Phantom JS - memory quota exceeded errors

### ISSUE THREAD

**Issue by tomgallagher** [jnicklas/capybara#1635]
Hello

Some background: Rails app. Background jobs. I'm running Sidekiq with multiple theads, each one of them is using Capybara, Poltergeist and PhantomJS in order to test and take screenshots of different pages.

I'm hitting critical memory quota exceeded errors in my worker. It seems highly likely that I'm collecting multiple instances of PhantomJS on my worker, despite the jobs finishing as expected.

I would really like to try something like Capybara::Session.close or Capybara::Session.quit, in a teardown routine at the end of my Sidekiq job and see if that makes a difference. I can't see how to do this.

Any help would be massively appreciated.

Tom

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the readme

**Comment by tomgallagher** [comment]
OK will do. Apologies.
