### ISSUE TITLE
Using Capybara.app_host remove # symbol when open URL in browser (Capybara v3.0)

### ISSUE THREAD

**Issue by askaa** [jnicklas/capybara#1641]
Steps to reproduce:
Capybara.app_host = 'http://example.com/#/'
Capybara.visit('line/1')

ExpR: Opens http://example.com/#/line/1
ActR: Opens http://example.com/line/1

**Comment by twalpole** [comment]
I'm curious as to why you'd ever set Capybara.app_host to 'http://example.com/#/'   ??

**Comment by abotalov** [comment]
I guess such approach is used sometimes for single page applications.

**Comment by twalpole** [comment]
@abotalov In that case I think one should just call visit('#/line/1')  then so it's clear in the test you're setting the target - otherwise calling visit('line/1') is going to be pretty confusing to most people

**Comment by twalpole** [comment]
IMHO this behavior wouldn't make sense -- if you want to visit based on the target portion of the URL then include the '#' in the visit method, otherwise the test becomes ambiguous
