### ISSUE TITLE
visit error 

### ISSUE THREAD

**Issue by whitelka** [jnicklas/capybara#1652]
Hello,
I'm using capybara, to visit page, I put path such as "admin_root_path" but I got an error 

     Failure/Error: visit admin_root_path
     NoMethodError:
       undefined method `+' for nil:NilClass
     # /Users/whitelka/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/session.rb:227:in `visit'

It's really hard to fix.. Please let me know why it works like this. Actually this code was going well few months ago but I don't know why it's not working now.

Thank you!

**Comment by Sa-ryong** [comment]
Same here. The error was introduced at version 2.6.0.

**Comment by twalpole** [comment]
What do you have Capybara.app_host set to?

**Comment by Sa-ryong** [comment]
Oh, I was testing scoped route. For me, Capybara.app_host is set to "op.lvh.me:3000".

**Comment by abotalov** [comment]
This url lacks a scheme. It should probably be `http://op.lvh.me:3000`

**Comment by twalpole** [comment]
Yeah -- it's unfortunate naming since Capybara.app_host (as shown in the readme) really is more of a base_url than a hostname -- change it to what @abotalov has specified and the issue should go away - If not we can reopen this
