### ISSUE TITLE
Setting a cookie with javascript doesn't work with Poltergeist and/or PhantomJS drivers

### ISSUE THREAD

**Issue by tansaku** [jnicklas/capybara#1653]
Is there any work in progress that will address the issue raised in this SO post:

http://stackoverflow.com/questions/17203986/setting-a-cookie-with-javascript-doesnt-work-in-poltergeist-and-or-phantomjs

And in particular a good way of addressing this issue without going through the deprecated browser method?

Many thanks in advance

**Comment by twalpole** [comment]
Ask questions on the mailing list as requested in the README,and when you do make it clear what exactly you're asking about since that SO question has an accepted answer

**Comment by tansaku** [comment]
thanks @twalpole - sorry but I'd prefer not to have to join a mailing list in order to ask questions.  The SO question has an accepted answer, but it uses a deprecated method on Capybara which seems like bad practice.  I guess we'll just live with it for the time being.
