### ISSUE TITLE
Multiple files uploading test

### ISSUE THREAD

**Issue by TeTiRoss** [jnicklas/capybara#1657]
I have issue with testing uploading multiple files with `capybara` using `cocoon`. How can I find all fields with id: "image" and attach to each of them file?

I found some decision, but it don`t work:
``` ruby

<%= f.file_field :image, required: false, class: "attach_file" %>
```

``` ruby
  click_link "Add photo"
  wait_for_ajax

  click_link "Add photo"
  wait_for_ajax


  page.all(:class, '.attach_file').each do |el|
    attach_file( el, "#{Rails.root}/spec/assets/example.jpg")
  end

  click_button "Add"

  expect(Post.count).to eq(1)
  expect(Post.last.images.size).to eq(2)

```
Error: `Unable to find file field #<Capybara::Element tag="input" path="/html/body/div/div/div/form[@id='new_post']/div[@id='educations']/div[1]/input[@id='image']">`

**Comment by twalpole** [comment]
questions on how to use capybara are not issues.  Please post questions to the mailing list as requested in the README
