### ISSUE TITLE
All feature tests were failed, cause I have a module named Addressable?

### ISSUE THREAD

**Issue by cod7ce** [jnicklas/capybara#1661]
Hi @jnicklas 
I got  a module named `addressable` in `app/models/concerns`, to manage `addresses` `phones` and `faxes`. After I upgrade `capybara` to latest version, all my feature tests were failed. And failure message: 
```ruby
undefined method `addresses' for #<User:0x0000000414b870>
```
I noticed version 2.6.2 is forced dependency on gem `addressable`, did it override my `Addressable` ? and what need I do?

Any thoughts?

**Comment by twalpole** [comment]
Move Capybara back to 2.5.x, or change/scope the name of your addressable module

**Comment by kofronpi** [comment]
Why should client code be changed because of a test dependency ? That is still an issue imho.

**Comment by twalpole** [comment]
@kofronpi - so if you had an app dealing with rodents that happened to have a Capybara model in it, you would require Capybara to change its class/module names so you can use it to test?
