### ISSUE TITLE
'execute_script' should accept optional '*args' attribute.

### ISSUE THREAD

**Issue by tommyh** [jnicklas/capybara#1662]
Hi,

First off - I've been using capybara for a few years now and i love it.  So thanks for all the hard work.  :)

Feature request: `execute_script` should accept optional `*args` attribute.

Note: I'm more than happy to work on a pull request for this feature, but wanted to open an issue first to discuss to see if this had already been thought of and not implemented for some reason.

Use case: I am using site_prism as my page object model and sometimes I want to execute javascript on one of the selenium elements which I have in my object model.

So instead of writing:

```ruby
execute_script("$('.login').fooBar();")
```

I could write:

```ruby
execute_script("$(arguments[0]).fooBar();", @home.login_bar.native)
```

(where `@home.login_bar` is my site_prism element)

One reason I can come up with why capybara's execute_script only takes one argument, and selenium webdriver takes 2 arguments (js and elements), is that either of the other drivers (poltergiest, capybara-webkit) only support the one js argument.  But I haven't invested the time to see if it's possible in the other drivers under the covers or they just chose to leave it out in the public ruby api as well.

Right now I am simply doing:

```ruby
page.driver.browser.execute_script("$(arguments[0]).fooBar();", @home.login_bar.native)
```

But it would be more convenient if I didn't have to think about the interface difference.  And it took me a far amount of googling/experimentation to even get that to work, so I think capybara supporting it (even if for supported drivers) would be helpful to others.

Thanks,
Tom

**Comment by twalpole** [comment]
This has been discussed before, and as you surmised the issue is whether or not it's possible to pass element references to the browser in the other available drivers.  It requires elements having a unique id that can be sent back and forth.  When this was previously discussed it wasn't possible in at least one other driver available at the time, not sure if that has changed.   We try not to add functionality that can't be implemented in other drivers because that ends up being just as bad as calling methods through page.driver (from a cross driver test usage perspective) but with the added benefit of not being able to tell it's not cross driver compatible

**Comment by tommyh** [comment]
Gotcha, I've confirmed that the other drivers don't have it in their public api, and I'm not motivated enough to chase down if the unique id requirement has been improved.

Glad you gave me this feedback before I invested time in a pull request.  :)

Now that I think of it, I might try monkey patching this behavior in our project.  If I do that, I'll post that code on this issue if it would help others.

Thanks again,
Tom

**Comment by tommyh** [comment]
If you are only using one driver (ie Selenium because you're using Sauce Labs), then here's a monkey patch which has been working well for me so far:

```ruby
class Capybara::Session
  def execute_script(script, *args)
    @touched = true
    driver.execute_script(script, *args)
  end

  def evaluate_script(script, *args)
    @touched = true
    driver.evaluate_script(script, *args)
  end
end

class Capybara::Selenium::Driver
  def execute_script(script, *args)
    browser.execute_script(script, *args)
  end

  def evaluate_script(script, *args)
    browser.execute_script("return #{script}", *args)
  end
end
```
