### ISSUE TITLE
Rails 5: Doesn't work with action_cable

### ISSUE THREAD

**Issue by smarquez1** [jnicklas/capybara#1663]
Hi,
I'm using the Rails 5 beta 3 with action cable, the integration works fine in development but when I try a feature test through capybara, it doesn't seem to hit the channel actions.

I'm using Portergeist and configured puma as capybara's server. Also I'm using es5-shim and es6-shim.

Has anyone else experienced this or knows any workaround?

Thanks!

**Comment by twalpole** [comment]
Use the master branch and specify `Capybara.server = :puma`
