### ISSUE TITLE
Observers not firing in feature/integration tests using Rails/Capybara

### ISSUE THREAD

**Issue by gregblass** [jnicklas/capybara#1666]
My observers work fine in my app and in my regular tests, but Capybara feature tests do not trigger any observers, no matter what I try. Has anyone dealt with this or is this a known or intentional behavior?

I'm using the latest version of RSpec, Capybara (github masters) and Rails 5.0.0beta3.

**Comment by twalpole** [comment]
Ask questions on the mailing list as requested in the README

**Comment by gregblass** [comment]
Sorry about that, and done.

**Comment by phereford** [comment]
Linking to the mailing list post:
https://groups.google.com/forum/#!searchin/ruby-capybara/rails-observers/ruby-capybara/lRb_i_52O6g/M5lHyjKoKQAJ
