### ISSUE TITLE
Cannot compose capybara matchers

### ISSUE THREAD

**Issue by agross** [jnicklas/capybara#1680]
RSpec expectations allows you to [compose matchers](https://www.relishapp.com/rspec/rspec-expectations/v/3-4/docs/compound-expectations) with `and` (`&`) and `or` (`|`).

It seems it's not possible to use composed matchers with capybara:

```ruby
expect(page).to have_content('foo') | have_content('bar')

=> NoMethodError: undefined method `|' for #<Capybara::RSpecMatchers::HaveText:0x000000073fd188>
```

(I also tried with `or`)

**Comment by twalpole** [comment]
This is tested for in the specs so it should work, make sure rspec/expectations is required before capybara.

**Comment by agross** [comment]
Thanks, running `RSpec.configure` before requiring capybara did the trick.
