### ISSUE TITLE
Cannot upload 2 images

### ISSUE THREAD

**Issue by yongquanben** [jnicklas/capybara#1681]
When i try to upload 1 image for testing, it works fine.
However, I hit an error when I upload 2 images (2 single file upload) 
Any kind soul to help on this issue i faced?

Below is my code with the error encountered.

attach_file 'category_image', "spec/support/images/test.jpg"
attach_file 'category_banner', "spec/support/images/test.jpg"

NoMethodError:
       undefined method `banner_will_change!' for #<Category:0x007f8cd9a80e18>
       Did you mean?  name_will_change!

**Comment by twalpole** [comment]
Please ask howto questions in the mailing list as requested at the top of the README - you'll want to post a stacktrace for the error when you do.
