### ISSUE TITLE
`#save_path` only works for pages, not screenshots

### ISSUE THREAD

**Issue by f3ndot** [jnicklas/capybara#1683]
gem version 2.7.0
also using gem `capybara-screenshot` 1.0.12

### Steps to Reproduce

1. Setup `env.rb` with `Capybara.save_and_open_page_path = 'tmp/screenshots'`
2. Run your tests with a failure
3. Observe that there is a deprecation warning to use `#save_path` instead
4. Observe that there are both the .png (screenshot) and .html (page) files in `./tmp/screenshots`
5. Change the line in `env.rb` to `Capybara.save_path = 'tmp/screenshots'`
6. Run your tests with a failure

### Expected

To see two files in `./tmp/screenshots`, the .png screenshot and the .html file

### Actual

The .png screenshot shows up in working directory (`.`) whereas the .html respects the configuration and shows up in `./tmp/screenshots`

**Comment by twalpole** [comment]
capybara-screenshot passes absolute paths to `#save_screenshot` and has not been updated to use `#save_path` - If you call page.save_screenshot yourself you will see that it does use `#save_path` when passed a relative path (or nothing).

Closing since it's an issue in capybara-screenshot
