### ISSUE TITLE
test different timezones

### ISSUE THREAD

**Issue by tansaku** [jnicklas/capybara#1685]
We've got a bug in our code that shows up depending on the users browser timezone.  We've been able to fix it, but would love to have an acceptance test to ensure it doesn't happen again, but we have trouble trying to influence the timezone that capybara is using for it's javascript operation (currently with poltergeist as the driver).

We've found a few resources online, e.g. 

http://stackoverflow.com/questions/19532425/how-to-stub-a-specific-timezone-for-capybara-testing

and have tried setting the timezone via the command line setting of env vars, and also using the zonebie gem to no avail:

```
TZ='BST' bec features/events/list_repeating_events.feature
ZONEBIE_TZ="Europe/London"  bec features/events/list_repeating_events.feature
```

Any ideas how we could manipulate the timezone that capybara/poltergeist (or other js driver) things they are running in?

Many thanks in advance

**Comment by twalpole** [comment]
Please ask howto questions on the mailing list as requested in the README - also note that TZ in the "browser" is not a function Capybara has any control over - although the specific driver you're using may be able to set it.

**Comment by tansaku** [comment]
apologies - sorry - most other projects are happy to get general questions in their issues and I keep forgetting that capybara is an exception to that.  Thanks for your input.
