### ISSUE TITLE
Enhance README.md with multiple sessions example

### ISSUE THREAD

**Issue by mikejramsey56** [jnicklas/capybara#1686]
I found the discussion on stackoverflow [multiple-sessions-in-capybara](http://stackoverflow.com/questions/36712779/multiple-sessions-in-capybara/36721112?noredirect=1#comment61033495_36721112) very enlightening. Please include the examples in the Capybara README.md. I believe that others would benefit.  Thank you.

**Comment by twalpole** [comment]
Fixed via README update
