### ISSUE TITLE
Capybara save_and_open_page_path and save_path problems?

### ISSUE THREAD

**Issue by AntonTrapp** [jnicklas/capybara#1688]
Please have a look at https://github.com/mattheworiordan/capybara-screenshot/issues/170

After I **upgraded Capybara to 2.7.0** the screenshot gem produced the **screenshots in the project root instead of the default tmp/capybara** and deleted my project directory (really happy to commit to local git very often *lol*).

When I set the path with **save_and_open_page_path it is working** but warning about the deprecation. With **save_path** I can remove the deprecation warning but it **is competely ignored** and all the files are comming to the project root directory again. That's my main reason to think that Capybara has a problem (I only **use** the two awesome gems, so it's just a noob guess)

**Comment by twalpole** [comment]
capybara-screenshot passes absolute paths to capybara, if it's ignoring save_path it's because it hasn't yet been updated to be compatible with capybara 2.7

**Comment by AntonTrapp** [comment]
Thank you very much for the information!

**Comment by mattheworiordan** [comment]
@twalpole thanks for the response.  To save me trawling through the changes in 2.7, any chance you can suggest what needs to change to be compatible then?

**Comment by twalpole** [comment]
@mattheworiordan The first thing save_page and save_screenshot do is call [prepare_path](https://github.com/jnicklas/capybara/blob/master/lib/capybara/session.rb#L729) passing in the filename/path passed to them and the default extension types (html/png).  If Capybara.save_path is defined Capybara should handle relative filenames correctly and you should be able to just pass a relative filename/path and it should save in the right place (or use Capybara.save_path to build an absolute path), if save_path is not defined and the previous Capybara.save_and_open_page_path is non nil you need to do what you were previously doing.
