### ISSUE TITLE
Find() doesn't match a CSS class with dots in the name

### ISSUE THREAD

**Issue by ramunasm** [jnicklas/capybara#1699]
Hello there,

I have a CSS class with multiple dots in it's name. I'm trying to use the following:
```ruby
find(".my.very.important.class").click
```

The HTML itself looks like this:
```html
<button type="button" id="tC0Qrj0" class="someclass my.very.important.class someotherclass onemoreclass">button</button>
```

And it seems that Capybara is not finding the class I need. I keep getting:
`Unable to find css ".my.very.important.class"`

Do I need to somehow escape the dots in the class name, or is this not supported at all?

Thank you!

P.S Using Capybara 2.6.2

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README - or read up on CSS escaping just as you would have to do to target that class in a normal .css file
