### ISSUE TITLE
2.7.1 : On fully dynamically generated page, everything is a stale element

### ISSUE THREAD

**Issue by akseiya** [jnicklas/capybara#1701]
I am navigating through a Rails-backed website with Backbone and Bootstrap on front-end.
Sign in page doesn't pose any problems, but return from the click on sign-in button takes a few extra seconds after the home page has loaded (in chromedriver).
All pages for signed-in user are almost entirely dynamically generated.
Everything (including `page.find(:xpath,'//html')`) is a stale element on the page for Capybara, while direct use of Selenium suggests no problems at all. PhantomJS doesn't render the page at all, although using Capybara finders gets me `ObsoleteNode` rather than failing to find anything.

```ruby
> page.driver.find_css '#app-navigation'
```
```
=> [#<Capybara::Selenium::Node tag="div" path="/html/body/div[1]/nav/div/div[2]">]
```
```ruby
> find '#app-navigation'
```
```
Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=50.0.2661.75)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-36-generic x86_64)
from /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
```

More backtrace `find(:xpath,'//html')`:
```
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:604:in `find_elements_by'
     # /var/lib/gems/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/search_context.rb:84:in `find_elements'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/selenium/node.rb:142:in `find_xpath'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:108:in `find_xpath'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:112:in `block in resolve_for'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:81:in `synchronize'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:108:in `resolve_for'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:35:in `block in find'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /var/lib/gems/2.1.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:33:in `find'
```

**Comment by twalpole** [comment]
are you inside a within block?  if so the element you are within has probably been removed from the page.  If not, we need a minimal reproducible example to debug this.

**Comment by akseiya** [comment]
@twalpole : 
No, no `within` in this case. I actually tried to use `#app-navigation` as selector for a `within` initially and then realized the error pops up even for a plain `find(:xpath,'//html')`.
I'm not sure how to proceed with minimal reproducible debug. Between submitting the sign-in form and the attempt to access the dashboard page there is a lot of proprietary code at work.

**Comment by akseiya** [comment]
In case the problem was not flaky enough, it doesn't reoccur today. Transition from sign-in page to dashboard is fluid, there's no delay in `irb`'s return from `click_button 'Sign in'`, Capybara finders work fine.

**Comment by twalpole** [comment]
I would say look at whatever code was changed between yesterday and today - anyway doesn't seem like its actually an issue in Capybara - closing

**Comment by akseiya** [comment]
It was indeed a `within`, just a one I did miss, apologies for the waste of time.
