### ISSUE TITLE
Disable Automatic Redirection

### ISSUE THREAD

**Issue by rsiddle** [jnicklas/capybara#1704]
I cannot seem to find an option to disable automatic redirection. I need to test the redirect whether it's a 301 or 302 header response.

**Comment by twalpole** [comment]
Capybara is designed to mimic a user - they don't see the redirect response, they see the page redirected to - hencen most Capybara drivers don't provide it to you.   You can technically do it with the rack_test driver by registering one created with the `follow_redirects: false` option but it usually easier to just test for redirect responses in your controller specs/tests.
