### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tibastral** [jnicklas/capybara#1705]
Hello,

I have a warning in capybara when passing to rails 5.0.rc1.

DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1 (called from process at /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:61)

Thank you for your amazing gem !

**Comment by twalpole** [comment]
The `env` being accessed there is a passed in parameter - not sure why that would be generate a rails deprecation - do you have a bigger stack trace?

**Comment by tibastral** [comment]
Nop, since it's not an error, but just a deprecation, no idea...

**Comment by twalpole** [comment]
hmnmm -- I'm not seeing it in any of my projects using 5.0.0.rc1 -- what other gems are you using?

**Comment by twalpole** [comment]
also you can open your copy of the  capybara gem and add a break (pry, byebug, etc) where the deprecation is coming from and look at the stack trace there to see if it provides any clue

**Comment by tibastral** [comment]
That's the trace :

/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:62:in `process'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:39:in `block in process_and_follow_redirects'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:38:in `times'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:38:in `process_and_follow_redirects'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/browser.rb:27:in `submit'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/form.rb:78:in `submit'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/rack_test/node.rb:62:in `click'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-rails-1.4.3/lib/cucumber/rails/capybara/javascript_emulation.rb:16:in `click_with_javascript_emulation'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/node/element.rb:135:in `block in click'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/node/base.rb:85:in `synchronize'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capybara-6b12bc496f1d/lib/capybara/node/element.rb:135:in `click'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/form_submitter.rb:38:in `rescue in submit_form'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/form_submitter.rb:35:in `submit_form'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/form_submitter.rb:5:in `fill_in_and_submit'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/form_submitter.rb:10:in `visit_and_create'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/admin_object_creator.rb:8:in `initialize'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/event_creator.rb:5:in `new'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/event_creator.rb:5:in `default_attributes'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/admin_object_creator.rb:9:in `initialize'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/contest_creator.rb:5:in `new'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/contest_creator.rb:5:in `default_attributes'
/Users/thibaut/goinfre/rushout/features/support/capybara_helpers/core/admin_object_creator.rb:9:in `initialize'
/Users/thibaut/goinfre/rushout/features/step_definitions/events_steps.rb:29:in `new'
/Users/thibaut/goinfre/rushout/features/step_definitions/events_steps.rb:29:in `block in <top (required)>'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_step_definition.rb:102:in `invoke'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/step_match.rb:27:in `invoke'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/step_match.rb:20:in `block in activate'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:31:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:11:in `test_case'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/bin/cucumber:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/cucumber:23:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/cli.rb:304:in `exec'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:27:in `block in <top (required)>'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:19:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

**Comment by twalpole** [comment]
I'm guessing its coming from your app or middleware used by your app and something is filtering the stack trace

**Comment by tibastral** [comment]
Nop my app is not using env

**Comment by twalpole** [comment]
@tibastral it doesn't have to be your code -- it could be middleware installed by some other gem -- the `env` referred to in the method in Capybara is a local variable hash that is passed in so there's no reason for that to output a deprecation notice, which would mean it has to be coming from some code called from the `send` - one last thing to try would be to open your copy of the actionpack gem and break when env is called and look at the stacktrace there -- I guess it's probably the env defined in  `actionpack/lib/action_controller/metal.rb`

**Comment by twalpole** [comment]
I'm closing this since I can't replicate it - If someone can provide an example that replicates it we can reopen.
