### ISSUE TITLE
Add an API for injecting the HTML into browser instead of visiting pages

### ISSUE THREAD

**Issue by skalee** [jnicklas/capybara#1707]
I propose extending the Capybara DSL with yet another method, `#replace_html`, which would literally replace the current page source code.

Or maybe there is such functionality already, but I haven't noticed it?

### The use case

I am developing a service which provides a set of JavaScript widgets which are intended to be embedded in 3rd-party websites. In order to test the widget, I need to prepare some trivial fake page. For example:

```html
<html><body>
    <!-- of course host and port below must be changed to match the server started by Capybara -->
    <script src="http://localhost:3000/access/the/widget.js" type="text/javascript"></script>
</body></html>
```

### What can I do now?

So far I've found 3 ways to work around the problem:

1. Provide some test controller and test view with this trivial page. Seems quite hacky cause these controller and view are useless outside of test environment. In fact, I should add some flow control into Rails routes to disable them in production.
2. Use https://github.com/oesmith/puffing-billy gem, but that seems to be an overkill. It adds bunch of dependencies, requires configuration, I had trouble to get it running. This approach is actually more difficult than it appears to be.
3. Inject the source code with JavaScript. It works, is not overcomplicated, but still hackish:

```ruby
    extend ActionView::Helpers::JavaScriptHelper

    execute_script <<-JS
      document.write("#{escape_javascript(html)}");
      document.close();
    JS
```

However I believe introducing yet another method is advocated.

### Other considerations

I'm not sure if the behavior of proposed method should be limited to replacing the page source code. Perhaps it should also make an entry in browser's history, like visit does. Perhaps it should also call `load` event on `window`.

**Comment by twalpole** [comment]
If you just want your own content to be loaded, create your own "app" and use that

    html = "whatever page content you want here"
    app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }
 
    sess = Capybara::Session.new(:selenium, app)
    sess.visit("/")  # will receive the content of html as the page

Modifying a pages content really isn't something the Capybara project needs/wants to do.

**Comment by 0xStarcat** [comment]
`Modifying a pages content really isn't something the Capybara project needs/wants to do.`

This may make sense to reconsider. For my project, it made sense to test partials and interaction behavior within partials that have different local_assigns, rather than entire pages. Figuring out how to use capybara methods like `find` and `click_button` with partials was not very user friendly. This solution solved my use case though by allowing me to "inject" a partial and access the `Capybara::Session` methods.

**Comment by twalpole** [comment]
@0xStarcat Why would you ever be interaction testing a partial?? A partial (as the name implies) is never used without the rest of a page - so just test the page.
