### ISSUE TITLE
Capybara broken with Firefox 47

### ISSUE THREAD

**Issue by twalpole** [jnicklas/capybara#1709]
FF 47 is broken when attempting to use with selenium-webdriver 2.53+ - Apparently a new release of FF should be coming next week that fixes this.  https://github.com/SeleniumHQ/selenium/issues/2110

**Comment by QuotableWater7** [comment]
Same problem for me.  I tried going to an older FF and then had other problems 😿

**Comment by twalpole** [comment]
@QuotableWater7 What other problems did you have -- you should be able to rollback to FF 46, turn off updates and be good to go.  This Issue was put here as an informational item to explain the current issue -- hopefully they release 47.0.1 soon

**Comment by QuotableWater7** [comment]
When I'm on FF 46, here is an issue I'm seeing:
```
Element is not clickable at point (570, 660.75). Other element would receive the click: <button aria-expanded="false" class="chalk-btn-danger dropdown-toggle approval-btn" data-toggle="dropdown" type="button"></button>
```

**Comment by QuotableWater7** [comment]
The spec runs perfectly on our CI though (we use Solano)

**Comment by twalpole** [comment]
@QuotableWater7 It's probably due to window size - so on your machine the default window size is different than on the CI setup and that leads to elements overlapping others (fixed header/footer, etc) - try resizing your window for that test.

**Comment by rafiqdeen** [comment]
how to rollback to FF 46 in Linux?

**Comment by twalpole** [comment]
@rafiqdeen It depends on what particular flavor of Linux you're using and which package manager.

**Comment by rafiqdeen** [comment]
@twalpole I am using ubuntu 14.04 LTS and I tried Synaptic package manager but it shows only 28.0 version.

**Comment by twalpole** [comment]
@rafiqdeen  http://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package/428778

**Comment by twalpole** [comment]
Firefox 47.0.1 has been released, and appears to also have issues with selenium-webdriver -  stick with 46.0.1 for now

**Comment by twalpole** [comment]
Firefox 47.0.1 works correctly with selenium-webdriver 2.53.4

**Comment by ZigmaZigmax** [comment]
Firefox 47.0.1 not working correctly, I am getting this

c:/ruby22/lib/ruby/2.2.0/net/http/generic_request.rb:25:in `initialize': HTTP request path is empty (ArgumentError)
        from c:/ruby22/lib/ruby/2.2.0/net/http/request.rb:14:in `initialize'
        from c:/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:95:in `new'

sometimes I am getting this

c:/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable': unable to obtain stable fi
refox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
        from c:/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
        from c:/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/socket_lock.rb:43:in `locked'

**Comment by twalpole** [comment]
@ZigmaZigmax  The errors you are getting are coming from selenium-webdriver and nothing to do with Capybara.  Capybaras own tests run with selenium-webdriver 2.53.4 and Firefox 47.0.1 without issue, so I would suggest making sure you are actually running FF 47.0.1 and that you don't have any hung processes hanging onto ports.  If both of those are fine check out the issue reports at the selenium project on github.

**Comment by ZigmaZigmax** [comment]
Oh, I am sorry, I am new to this, But I tried capybara, I thought selenium is the only driver to launch firefox, will capybara itself can launch Firefox and do UI functional test?
