### ISSUE TITLE
Tests that lie about ignore_hidden_elements

### ISSUE THREAD

**Issue by henrik** [jnicklas/capybara#1714]
If you search for "ignore_hidden_elements" in https://github.com/jnicklas/capybara/blob/master/lib/capybara/spec/session/has_text_spec.rb, there are two tests where the description and contents don't match up.

Just happened to see it looking into other stuff, and I don't know it enough to make a PR at this point, but thought I would report it at least.

``` ruby
  it "should be true if `Capybara.ignore_hidden_elements = true` and text is invisible." do
    Capybara.ignore_hidden_elements = false
    @session.visit('/with_html')
    expect(@session).to have_text('Some of this text is hidden!')
  end

  it "should be false if `Capybara.ignore_hidden_elements = true` and text is invisible." do
    Capybara.ignore_hidden_elements = false
    @session.visit('/with_html')
    expect(@session).not_to have_no_text('Some of this text is hidden!')
```

**Comment by twalpole** [comment]
Good catch! - fixed - thanks
