### ISSUE TITLE
New 'rack' gem release

### ISSUE THREAD

**Issue by kristineKronberga123** [jnicklas/capybara#1717]
Rack  is one of capybara dependenty, before it did not have any Ruby version requirements and could be instaled automaticly. But today a new rack gem was released (version 2.0.1). It has minimum requirement of Ruby 2.2.
This may cost a confision.
It would be good if capybara could restrict that rack up to verion 2 is used.

**Comment by twalpole** [comment]
Doing that would prevent people who are running ruby 2.2+ from using new rack gems, and Capybara has no issues itself running with the new rack.   This should not be a restriction specified in Capybara.
