### ISSUE TITLE
Broken Dependency

### ISSUE THREAD

**Issue by amitz** [jnicklas/capybara#1718]
Hello,

It seems like Rack 2.0 was released few days ago, and the latest version no longer supports Ruby 1.9.3. This breaks Capybara for Ruby 1.9.3 users.

Thanks.

**Comment by twalpole** [comment]
You need to specify rack < 2.0 in your projects Gemfile - Capybara will not be limiting the version of rack it supports since that would prevent people on modern versions of ruby from using rails 5

**Comment by amitz** [comment]
Isn't it possible to check for the current Ruby version and pick the right depenecy in the gemspec file?

**Comment by twalpole** [comment]
@amitz  - Not in any kind of reliable supported manner -  Really bundler/gem should add a feature to not consider gems that specify a ruby version above what you're running, but as of now thats not there.  Same issue occurred with mime-types 3 -- There's nothing Capybara can do about it, and the versions is not a dependency of Capybara so it shouldn't be specified as one.  It's a dependency of your projects decision to stay with 1.9.3 (which is really really out of date).

**Comment by amitz** [comment]
@twalpole - Fair enough. Thanks for detailed answer.
I'll state anyhow that the rack version that support Ruby 1.9.3 and should be forced in the Gemfile is "1.4.6" -(in-case someone will stumble upon this thread in the future with the same problem).

Thanks.
