### ISSUE TITLE
"method missing" for background and given.

### ISSUE THREAD

**Issue by Fahrenhei7** [jnicklas/capybara#1723]
undefined method `background' for RSpec::ExampleGroups::CreateNewAchievement:Class

I got errors like this when use "background" and "given" methods in rails 5. But with methods before and let everything goes great.

Rspec version 3.5.1
Capybara version 2.7.1

**Comment by twalpole** [comment]
@Fahrenhei7 Show an example test that gives this this error.

**Comment by Fahrenhei7** [comment]
```
require 'rails_helper'
require_relative '../support/login_form'
require_relative '../support/new_achievement_form'


feature 'create new achievement' do
  given(:new_achievement_form) { NewAchievementForm.new }
  given(:login_form) { LoginForm.new }
  given(:user) { FactoryGirl.create(:user) }

  background do
    login_form.visit_page.login_as(user)
  end

  scenario 'with valid data' do
    new_achievement_form.visit_page.fill_in_with(
      title: 'Read a book'
    ).submit

    expect(page).to have_content('Achievement has been created')
    expect(Achievement.last.title).to eq('Read a book')
  end

  scenario 'with invalid data' do
    new_achievement_form.visit_page.submit
    expect(page).to have_content("can't be blank")
  end
end
```

```
require 'rails_helper'
require_relative '../support/login_form'
require_relative '../support/quest/new_quest_form'

feature 'create new quest as logged in user' do

  given(:user) { FactoryGirl.create(:user) }
  given(:login_form) { LoginForm.new }
  given(:new_quest_form) { NewQuestForm.new }
  background do
    login_form.visit_page.login_as(user)
  end


  scenario 'with valid data' do
    new_quest_form.visit_page_by_click.fill_in_with_valid_data().submit
    expect(page).to have_content('Capybara new name')
  end

  scenario 'with invalid data' do
    new_quest_form.visit_page_by_click.fill_in_with_invalid_data().submit
    expect(page).to have_content("can't be blank")
  end

end
```

**Comment by twalpole** [comment]
Are you requiring 'capybara/rspec' somewhere?

**Comment by Fahrenhei7** [comment]
No. But I have this specs in spec/features and have
`config.infer_spec_type_from_file_location!`
in configuration of rspec.

**Comment by Fahrenhei7** [comment]
I tried, and even if i require 'capybara/rspec' somewhere in rails_helper, for example after 'rspec/rails' or wherever, I receive the same error.

**Comment by twalpole** [comment]
@Fahrenhei7 Not sure what to tell you -- background and let are aliases that are set up in rspec/capybara/features.rb  - https://github.com/jnicklas/capybara/blob/master/lib/capybara/rspec/features.rb#L3

There are set up via a shared_context that is applied to any test that has the metadata capybara_feature: true.  That metadata is set when you use `feature` which is defined in the same file.  I have no idea how your usage of `feature

**Comment by Fahrenhei7** [comment]
Thanks! I finally found the issue. I missed one step in including capybara. Just got misleading why everything from capybara workd, but the aliases. 
Thanks for your time! Sorry, for my inadvertence.
