### ISSUE TITLE
undefined method `background` after running sample code in rails 5

### ISSUE THREAD

**Issue by amingilani** [jnicklas/capybara#1724]
Hi, 

I get the following error:
```
/Users/gilani/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/example_group.rb:732:in `method_missing': undefined method `background' for RSpec::ExampleGroups::SigningIn:Class (NoMethodError)
Did you mean?  around
```
By copying the sample code from the README into my spec:

```ruby
require 'rails_helper'

feature 'Signing in' do
  background do
    User.make(email: 'user@example.com', password: 'caplin')
  end

  scenario 'Signing in with correct credentials' do
    visit '/sessions/new'
    within('#session') do
      fill_in 'Email', with: 'user@example.com'
      fill_in 'Password', with: 'caplin'
    end
    click_button 'Sign in'
    expect(page).to have_content 'Success'
  end

  given(:other_user) { User.make(email: 'other@example.com', password: 'rous') }

  scenario 'Signing in as another user' do
    visit '/sessions/new'
    within('#session') do
      fill_in 'Email', with: other_user.email
      fill_in 'Password', with: other_user.password
    end
    click_button 'Sign in'
    expect(page).to have_content 'Invalid email or password'
  end
end
```

## System Info

Stack:
```ruby
ruby '2.3.1'
gem 'rails', '~> 5.0.0'
```

-------------------------------------------------------------------------------------------

`rails_helper.rb`:
```ruby
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
```

-------------------------------------------------------------------------------------------

`spec/support/capybara.rb`:
```
require 'capybara/rspec'
require 'capybara/poltergeist'

Capybara.javascript_driver = :poltergeist
```

**Comment by amingilani** [comment]
Temporary fix: I got around the issue by replacing `background` with `before`, and `given` with `let`

**Comment by twalpole** [comment]
Duplicate of Issue #1723  - @Fahrenhei7 What was your configuration mistake?

**Comment by twalpole** [comment]
@amingilani I notice from your code sample that you are loading all files in spec/support/**/*.rb but you list your filename as rspec/support/capybara.rb (rspec vs spec) is that just a typo?

**Comment by amingilani** [comment]
@twalpole sorry, that was a typo, fixed, everything is in `spec/`

And YES! I had `config.shared_context_metadata_behavior = :apply_to_host_groups` because the comment above said:

```
  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3).
```

Changing it back fixed it!

I'm closing this issue, but can you please explain what happened? And if this will be a problem with Rspec 4 comes out?

**Comment by twalpole** [comment]
@amingilani The way Capybara includes the aliases into the tests uses shared contexts which in previous versions of RSpec would automatically get included based on metadata. If  shared_context_metadata_behavior == :trigger_inclusion (default in 3.5) that behavior continues, however if changed to :apply_to_host_groups that behavior changes and the automatic inclusion no longer happens.  The change in behavior makes sense for RSpec since it makes the API more in line with all the other places in the API metadata is used, and I'm working on a fix for it currently which will be included in Capybara 2.8

**Comment by amingilani** [comment]
@twalpole: Makes sense! Thank you for the explanation!

**Comment by twalpole** [comment]
@amingilani 09138cdcd74db3b3928d67ffbbc8010f860658f2 is the fix being merged into master, if you want to give it a try

**Comment by Fahrenhei7** [comment]
I just didn't require capybara in spec_helper. But it seems, he called require in support/.
