### ISSUE TITLE
Configuring wait_for_pending_requests()'s duration

### ISSUE THREAD

**Issue by hgani** [jnicklas/capybara#1727]
Hi,

Is there any way I can configure the duration of wait_for_pending_requests() ? 

This is really useful when using REPL (e.g. binding.pry) for debugging, because often we need to pause the execution more than 60 seconds to inspect variables etc.

Thanks

**Comment by twalpole** [comment]
Not currently, it's hard coded at 60 seconds, https://github.com/jnicklas/capybara/blob/master/lib/capybara/server.rb#L91

PRs welcome
