### ISSUE TITLE
Creating a Model Named MapLayer with layer_url as a field breaks all edit paths

### ISSUE THREAD

**Issue by Fladdermuz** [jnicklas/capybara#1729]
Any type of edit path edit_posts.. etc and even visit('/posts/1/edit') both return an error:
No Path matches "http:/127.0.0.1:3000/posts/1/MyText"
With MyText being the value I have in a fixture file map_layers.yml in the field layer_url.
Changing the fixture text to edit fixes the issue. Seems strange however.

**Comment by twalpole** [comment]
I'm not sure what this has to do with Capybara, sounds like you're redirecting requests and are shadowing one of your url helpers with a local attribute.  Capybara doesn't overwrite any route helpers, or have anything to do with them.

**Comment by Fladdermuz** [comment]
No and no. Just started after installing the Gem. Probably something else then.
