### ISSUE TITLE
Rails 5 and rack-test

### ISSUE THREAD

**Issue by cwyn** [jnicklas/capybara#1731]
Hi

I am trying to set up a test suite for a new Rails 5 app. I am getting
   `ArgumentError: rack-test requires a rack application, but none was given`
Happy to give more information on my set up to get some help please.

```
require 'capybara/rspec'
require 'capybara-webkit'
```

```
Capybara.configure do |config|
  config.run_server = false
  config.app_host = 'localhost:3000'
end
```

```
feature 'Visiting the home page' do
  scenario 'home' do
    visit '/'
    expect(page).to have_content('Home')
  end
end
```

As a side note I also tried with webkit driver in the configure block but got another error:
 ```
Failure/Error: visit '/'

     NoMethodError:
       undefined method `+' for nil:NilClass
     # /Users/***/.rvm/gems/ruby-2.3.1/gems/capybara-2.7.1/lib/capybara/session.rb:228:in `visit'
```

**Comment by twalpole** [comment]
Please ask howto questions on the mailing list as requested in the README
