### ISSUE TITLE
Last matcher

### ISSUE THREAD

**Issue by thehenster** [jnicklas/capybara#1733]
This idea has been [discussed before](https://github.com/jnicklas/capybara/pull/1101) but I thought I'd float a less in your face version. Something like..

```
click_link "Save", match: :last
```
or
```
fill_in "Title", match: :last
```
or
```
find(".item", match: :last)
```

If that still increases the size of the API more than the feature is worth it then no problem.

**Comment by twalpole** [comment]
I think the `click_link` and `fill_in` examples seem like they would be really rare cases and probably better served by just scoping to a region of the page.  Most cases of the `find` example are probably better served by doing something along the lines of `find("div.item:last-of-type")` which then doesn't have the downsides of #all/#first
