### ISSUE TITLE
After upgrading to Rails 5 - unit testing shows NoMethodError: undefined method `click' for nil:NilClass

### ISSUE THREAD

**Issue by salmagomaa** [jnicklas/capybara#1735]
I didn't have this error before upgrade (rails 4.2), but once I upgraded to rails 5.0.0, I got this error.

NoMethodError: undefined method `click' for nil:NilClass

I know that the HTML doesn't have the DOM element that is being clicked but I don't know why this error is now showing?

**Comment by twalpole** [comment]
Without you providing the code causing the error there is nothing we can say. I will reopen if you provide enough info for us to troubleshoot or you can ask for help on the mailing list as mentioned in the README.

**Comment by salmagomaa** [comment]
Thanks it was my code error!
