### ISSUE TITLE
has_field? not allowing to find by class is a limitation?

### ISSUE THREAD

**Issue by vizcay** [jnicklas/capybara#1755]
Hi, I've been using capybara for quite a time and always struggle with the situtation to check for fields (inputs) values changed after ajax or js given the case that they don't have a reliable name, id or label to match them.

I develop accounting applications where is quite common to have *tables* of things were records are added dinamically via JS. Given that:

* the inputs can't have a predefined id because they arent unique
* the name of the input is not known in the test, because they are added dinamically with a PLACEHOLDER inside that is dinamically replaced with Date().getTime() (so there aren't collisions)
* because they are inside tables, they don't have a label to match

Let's say for example I have this kind of test,

```
page.click_on 'Append'
within("table#items tbody tr:last-child") do
  page.find('input.unity_price').set '25'
  page.find('input.quantity').set '5'
  expect(page.find('input.subtotal').value).to eq '125.00'
end
```

In the last line we get intermitent results of course because it doesn't waits for js to finish (this is simple enought and it will, but you get the point). Now,

`expect(page).to have_field('.subtotal', with: '125.00')`

doesn't works because it only locates by id, label or name. Also,

`expect(page).to have_css('input.subtotal[value="125.00"]')`

won't work because the attribute is not the current value of the DOM.

So what I am missing here? What's the 'standard' way to write this kind of tests to wait for js?

Thanks, great piece of software by the way = )

**Comment by twalpole** [comment]
Assuming you're using a recent version of you could just do 

    expect(page).to have_field(with: '125.00')

assuming you're not going to have random other inputs in that row.  If you really want to verify it's the one with class of .subtotal you could do something like

    expect(page.find('input.subtotal')).to match_selector(:field, with: '125.00')

which will retry for the selector to change.  

If you're using the master branch you can just do

    expect(page).to have_field(class: 'subtotal', with: '125.00')

In the future please ask howto question in the mailing list as requested in the README

**Comment by vizcay** [comment]
twalpole:

Great, I think that 

`expect(page).to have_field(class: 'subtotal', with: '125.00')`

is by far the best syntax.. that will be on 2.8.2 ?

**Comment by twalpole** [comment]
@vizcay  It's a new feature so it will be in 2.9.0
