### ISSUE TITLE
attaching csv file results in UploadedFile with content-type of "text/comma-separated-values"

### ISSUE THREAD

**Issue by josh-m-sharpe** [jnicklas/capybara#1756]
I'm attaching a file to a file field like ths:

`attach_file('Csv', Rails.root.join('test', 'fixtures', 'push_notifications_valid_upload.csv'))`

If I debugger in the controller, I see this

```
(byebug) params["push_notification"]["push_notification_member_list"]["csv"]
#<ActionDispatch::Http::UploadedFile:0x007fe8922feef0 @tempfile=#<Tempfile:/var/folders/3y/t3n5r5d56wn2zl9z9byzx2_h0000gn/T/RackMultipart20160912-11407-wdnkf7.csv>, @original_filename="push_notifications_valid_upload.csv", @content_type="text/comma-separated-values", @headers="Content-Disposition: form-data; name=\"push_notification[push_notification_member_list][csv]\"; filename=\"push_notifications_valid_upload.csv\"\r\nContent-Type: text/comma-separated-values\r\nContent-Length: 60\r\n">

(byebug) params["push_notification"]["push_notification_member_list"]["csv"].content_type
"text/comma-separated-values"
```

If I attach the same file in a browser and submit, the content type is "text/csv" - so it seems that the test suite is incorrect.  Is this a bug?  Configuration problem?  Is there a way to stub the content type to the correct value?

Thanks!

Additional info I found:
"text/comma-separated-value" exists but appears to be flagged as obsolute here:
https://github.com/mime-types/mime-types-data/blob/master/types/text.yaml#L38-L45

**Comment by twalpole** [comment]
I assume you're using the rack-test driver?  The mime-types gem is used to select the first mime-type that matches the given filename.  According to the docs http://www.rubydoc.info/gems/mime-types/MIME/Types#type_for-class_method they should be sorted with non-obsolete before obsolete, however from your report it would appear that is not happening.  What version of mime-types are you suing?

**Comment by josh-m-sharpe** [comment]
2.99.2
I also tried bumping to 3.1 and that didn't help.

**Comment by twalpole** [comment]
Seems like mime-types sorting is fully broken then

**Comment by twalpole** [comment]
@josh-m-sharpe Please try the mime_types_broken branch and see if that fixes the issue for you.

**Comment by josh-m-sharpe** [comment]
Yep - that branch looks good!

**Comment by twalpole** [comment]
Fixed in master
