### ISSUE TITLE
has_field? not working with new syntax class: "XXX"

### ISSUE THREAD

**Issue by vizcay** [jnicklas/capybara#1766]
According to #1755 in 2.9.x we are going to be able to do:

`expect(page).to have_field(class: 'xxx', with: 'value')`

It's not working for me,
```

[1] pry(XXX)> page.has_field?(class: 'retencion_ganancias_numero_certificado')
=> false
[2] pry(XXX)> page.has_field?(class: '.retencion_ganancias_numero_certificado')
=> false
[3] pry(XXX)> page.find('.retencion_ganancias_numero_certificado')
=> #<Capybara::Node::Element tag="input" path="//HTML[1]/BODY[1]/DIV[1]/DIV[2]/DIV[1]/FORM[1]/DIV[10]/DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/INPUT[2]">
[4] pry(XXX)> page.find('.retencion_ganancias_numero_certificado').value
=> "00000001"
[5] pry(XXX)> page.has_field?(class: 'retencion_ganancias_numero_certificado', with: '00000001')
=> false
[6] pry(XXX)> Capybara::VERSION
=> "2.9.2"
```

The complete example,

```
    scenario 'crea nuevo' do
      visit new_empresa_pago_path(test_empresa)

      fill_in 'pago[fecha]',         with: '2016-09-03'
      fill_in 'pago[punto_emision]', with: '4'
      fill_in 'pago[numero]',        with: '1'
      select "#{proveedor.codigo} - #{proveedor.nombre}", from: 'pago[proveedor_id]'
      click_on 'retencion_ganancias_agregar'
      within '#tabla_retenciones_ganancias > tbody > tr:last-of-type' do
        find('.retencion_ganancias_fecha').set '2016-09-01'
        find('.retencion_ganancias_punto_emision').set '4'
        find('.retencion_ganancias_numero_certificado').click
        expect(page).to have_field(class: 'retencion_ganancias_numero_certificado', with: '00000001')
        ------- truncated --------

````

Poltergeist 1.10.0 / Phantomjs 2.1.1

**Comment by twalpole** [comment]
Unfortunately I may have mispoken in #1755 - and the ability to do it exactly like that may not be there until 2.10 (I have to read what I put in the release announcement and determine whether it can be released as a "bug" fix or whether its a "new" feature).  For now you should be able to do

    expect(page).to have_field(nil, class: 'xxx', with: 'value')

or

    expect(page).to have_selector(:field, class: 'xxx', with: 'value')

**Comment by vizcay** [comment]
Ok I will stick to, 

`expect(page).to have_selector(:field, class: 'xxx', with: 'value')`

that is working meanwhile.

Thanks

**Comment by vizcay** [comment]
@twalpole also I found this but not sure if it's a bug or not supported (hidden field):

```
[19] pry(XXX)> page.find('.retencion_ganancias_destroy', visible: false)
=> #<Capybara::Node::Element tag="input" path="//HTML[1]/BODY[1]/DIV[1]/DIV[2]/DIV[1]/FORM[1]/DIV[10]/DIV[1]/TABLE[1]/TBODY[1]/TR[1]/TD[2]/INPUT[6]">
[20] pry(XXX)> page.has_selector?(:field, class: 'retencion_ganancias_destroy', visible: false)
=> false
[21] pry(XXX)> page.has_selector?(:field, class: 'retencion_ganancias_destroy', visible: false, type: 'hidden')
=> false
```

**Comment by twalpole** [comment]
@vizcay  The :field selector - https://github.com/jnicklas/capybara/blob/master/lib/capybara/selector.rb#L53 - is specifically defined not to include fields of type 'hidden'.  To test for that you'd need to do something like

    expect(page).to have_css('input[type="hidden"].retencion_ganancias_destroy', visible: false)

or if you're doing it a lot, create your own custom selector

    Capybara.add_selector(:hidden_field) do
       xpath(:name) do |locator, options|
         xpath = XPath.descendant(:input)[XPath.attr(:type).equals('hidden')]
         locate_field(xpath, locator, options)
       end
    end

which you could then use as 

    page.has_selector?(:hidden_field, class: 'retencion_ganancias_destroy', visible: false)

The need to pass 'visible: false' to that is unfortunate so I should probably implement a way for selectors to override the default visibility setting in a future release

**Comment by vizcay** [comment]
@twalpole yes but usually I'm checking the value of a field:

`expect(page).to have_css('input[type="hidden"][value="xxx"].retencion_ganancias_destroy', visible: false)`

that looks like too much.. so I will explore the custom selector route.. this will be ideal:

`page.has_selector?(:hidden_field, class: 'retencion_ganancias_destroy', with: 'xxx')`

Thanks

**Comment by twalpole** [comment]
@vizcay to  add value checking to the custom selector, just add a 'with' filter (or import it from the field filter set)

```
Capybara.add_selector(:hidden_field) do
   xpath(:name) do |locator, options|
     xpath = XPath.descendant(:input)[XPath.attr(:type).equals('hidden')]
     locate_field(xpath, locator, options)
   end

   filter(:with) do |node, with|
     with.is_a?(Regexp) ? node.value =~ with : node.value == with.to_s
   end
end
```
or

```
Capybara.add_selector(:hidden_field) do
   xpath(:name) do |locator, options|
     xpath = XPath.descendant(:input)[XPath.attr(:type).equals('hidden')]
     locate_field(xpath, locator, options)
   end

   filter_set(:field)  # import all filters from the :field selector 
   #filter_set(:field, [:with])  #only import the :with filter from the :field selector
end
```

**Comment by twalpole** [comment]
@vizcay Just as a note -- the reason to implement the :with filter through a filter rather than through the xpath/css expression (like the :name expression filter in the example above) is that you usually want to be testing the current value property whereas the xpath/css query would test the attribute as it was set when the page loaded.
