### ISSUE TITLE
Chrome opens data:, instead of URL

### ISSUE THREAD

**Issue by Logout22** [jnicklas/capybara#1783]
## Meta
Capybara Version:
2.10.1
Driver Information (and browser if relevant):
selenium-webdriver 3.0.0 with Chrome 54.0.2840.90

## Expected Behavior
Chrome should open the URL passed in at Session.visit()

## Actual Behavior
Chrome opens data:, and visit() fails

## Steps to reproduce
    @session = Capybara::Session.new(Capybara.current_driver)
    @session.visit <URL>
    # Chrome does not open the URL

**Comment by Logout22** [comment]
I removed the .chromedriver-helper directory in my home, and then it worked. Must have been misconfigured accidentally. Sorry!

**Comment by kikocastro** [comment]
Same problem here 
`Chrome 54.0.2840.98`
`chromedriver 2.25.426935`
Anyone else got this and solved it?
