### ISSUE TITLE
Text string is being interpolated as HTML

### ISSUE THREAD

**Issue by ronwsmith** [jnicklas/capybara#1788]
## Meta
capybara (2.10.1)

Occurs for both:
poltergeist (1.11.0) with phantomjs 2.1.1
selenium-webdriver (2.53.4) with firefox 47.0.1

## Expected Behavior

`.text` that returns a string should be able to use `have_content` against all parts of that string

## Actual Behavior

When the string includes HTML, `have_content` appears to interpolate the string as HTML and only searches what would be rendered to a user.

## Steps to reproduce

HTML:
```html
<div id="text-link">
  &lt;a href=&quot;https://www.domain.com/test&quot;&gt;Link Text&lt;/a&gt;
</div>
```

Renders on the page to:
```HTML
<a href="https://www.domain.com/test">Link Text</a>
```

Capybara:
```ruby
> find('#text-link').text
=> "<a href="https://www.domain.com/test">Link Text</a>"

> expect(find('#text-link').text).to have_content "/test"
RSpec::Expectations::ExpectationNotMetError: expected to find text "/test" in "Link Text"
from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib/rspec/support.rb:87:in `block in <module:Support>'
```

Note: This is not an urgent issue by any means as the following works:

```ruby
expect(find('#text-link')).to have_content "/test"
```

**Comment by twalpole** [comment]
You're trying to use have_content incorrectly.  Like all of Capybaras matchers they are used with elements.  If you call it on text `Capybara.string` is used to convert that text to elements by parsing it as HTML.  The correct usage is as you show at the end

    expect(element).to have_content("expected content")    # have_text/have_content are the same

**Comment by ronwsmith** [comment]
Appreciate the insight @twalpole .  I wasn't familiar with the `Capybara.string` behavior.

Note to anyone else reading this issue: `has_content?` throws a `NoMethodError` on a string, but `have_content` converts it to an element.

**Comment by twalpole** [comment]
@ronwsmith Yes because `has_content?` is a method on Capybara::Node::Element - `have_content` is an RSpec matcher - they're completely different things.  If you're working with strings you should just be using the normal string methods and/or RSpec matchers designed for working with strings
